/* คลังคำ: ตัวละครดัง — เลือกเฉพาะตัวที่มีลักษณะเด่นพอจะวาดได้
   หมวด: cartoon / anime / movie / game
   หมายเหตุ: เก็บเป็นชื่อข้อความเท่านั้น ไม่มีรูปตัวละครใน repo นี้ */

window.WORDS_CHARACTERS = [

  /* ---------- การ์ตูน ---------- */
  { w: "มิกกี้เมาส์", en: "Mickey Mouse", cat: "cartoon", lv: 1 },
  { w: "มินนี่เมาส์", en: "Minnie Mouse", cat: "cartoon", lv: 1 },
  { w: "โดนัลด์ ดั๊ก", en: "Donald Duck", cat: "cartoon", lv: 1 },
  { w: "กูฟฟี่", en: "Goofy", cat: "cartoon", lv: 2 },
  { w: "วินนี่ เดอะ พูห์", en: "Winnie the Pooh", cat: "cartoon", lv: 1 },
  { w: "สปันจ์บ็อบ", en: "SpongeBob", cat: "cartoon", lv: 1 },
  { w: "แพทริก", en: "Patrick Star", cat: "cartoon", lv: 1 },
  { w: "ทอมกับเจอร์รี่", en: "Tom and Jerry", cat: "cartoon", lv: 1 },
  { w: "บั๊กส์ บันนี่", en: "Bugs Bunny", cat: "cartoon", lv: 2 },
  { w: "สคูบี้ดู", en: "Scooby-Doo", cat: "cartoon", lv: 2 },
  { w: "ชเร็ค", en: "Shrek", cat: "cartoon", lv: 1 },
  { w: "มินเนียน", en: "Minion", cat: "cartoon", lv: 1 },
  { w: "วู้ดดี้", en: "Woody", cat: "cartoon", lv: 2 },
  { w: "บัซ ไลท์เยียร์", en: "Buzz Lightyear", cat: "cartoon", lv: 1 },
  { w: "ซิมบ้า", en: "Simba", cat: "cartoon", lv: 1 },
  { w: "นีโม่", en: "Nemo", cat: "cartoon", lv: 1 },
  { w: "โดรี่", en: "Dory", cat: "cartoon", lv: 2 },
  { w: "โอลาฟ", en: "Olaf", cat: "cartoon", lv: 1 },
  { w: "เอลซ่า", en: "Elsa", cat: "cartoon", lv: 1 },
  { w: "สติทช์", en: "Stitch", cat: "cartoon", lv: 1 },
  { w: "ซินเดอเรลล่า", en: "Cinderella", cat: "cartoon", lv: 2 },
  { w: "สโนว์ไวท์", en: "Snow White", cat: "cartoon", lv: 2 },
  { w: "เงือกน้อยแอเรียล", en: "Ariel", cat: "cartoon", lv: 2 },
  { w: "อะลาดิน", en: "Aladdin", cat: "cartoon", lv: 2 },
  { w: "พิน็อกคิโอ", en: "Pinocchio", cat: "cartoon", lv: 1 },
  { w: "ปีเตอร์แพน", en: "Peter Pan", cat: "cartoon", lv: 2 },
  { w: "ทิงเกอร์เบลล์", en: "Tinker Bell", cat: "cartoon", lv: 2 },
  { w: "บาร์ต ซิมป์สัน", en: "Bart Simpson", cat: "cartoon", lv: 1 },
  { w: "โฮเมอร์ ซิมป์สัน", en: "Homer Simpson", cat: "cartoon", lv: 1 },
  { w: "พาวเวอร์พัฟเกิร์ล", en: "Powerpuff Girls", cat: "cartoon", lv: 2 },
  { w: "แองกรี้ เบิร์ด", en: "Angry Birds", cat: "cartoon", lv: 1 },
  { w: "โพรอน", en: "Doraemon's bell", cat: "cartoon", lv: 3 },

  /* ---------- อนิเมะ / มังงะ ---------- */
  { w: "โดราเอมอน", en: "Doraemon", cat: "anime", lv: 1 },
  { w: "โนบิตะ", en: "Nobita", cat: "anime", lv: 1 },
  { w: "ปิกาจู", en: "Pikachu", cat: "anime", lv: 1 },
  { w: "โปเกบอล", en: "Poke Ball", cat: "anime", lv: 1 },
  { w: "นารูโตะ", en: "Naruto", cat: "anime", lv: 1 },
  { w: "ซาสึเกะ", en: "Sasuke", cat: "anime", lv: 2 },
  { w: "คาคาชิ", en: "Kakashi", cat: "anime", lv: 2 },
  { w: "ลูฟี่", en: "Luffy", cat: "anime", lv: 1 },
  { w: "โซโล", en: "Zoro", cat: "anime", lv: 2 },
  { w: "ช็อปเปอร์", en: "Chopper", cat: "anime", lv: 2 },
  { w: "โกคู", en: "Goku", cat: "anime", lv: 1 },
  { w: "เบจิต้า", en: "Vegeta", cat: "anime", lv: 2 },
  { w: "ดราก้อนบอล", en: "Dragon Ball", cat: "anime", lv: 1 },
  { w: "โคนัน", en: "Detective Conan", cat: "anime", lv: 1 },
  { w: "ชินจัง", en: "Crayon Shin-chan", cat: "anime", lv: 1 },
  { w: "มารุโกะจัง", en: "Chibi Maruko-chan", cat: "anime", lv: 2 },
  { w: "เซเลอร์มูน", en: "Sailor Moon", cat: "anime", lv: 1 },
  { w: "โทโทโร่", en: "Totoro", cat: "anime", lv: 1 },
  { w: "แมวรถบัส", en: "Catbus", cat: "anime", lv: 3 },
  { w: "คิตตี้", en: "Hello Kitty", cat: "anime", lv: 1 },
  { w: "ริลัคคุมะ", en: "Rilakkuma", cat: "anime", lv: 2 },
  { w: "อันปังแมน", en: "Anpanman", cat: "anime", lv: 2 },
  { w: "อุลตร้าแมน", en: "Ultraman", cat: "anime", lv: 1 },
  { w: "ไอ้มดแดง", en: "Kamen Rider", cat: "anime", lv: 2 },
  { w: "กันดั้ม", en: "Gundam", cat: "anime", lv: 1 },
  { w: "ทันจิโร่", en: "Tanjiro", cat: "anime", lv: 2 },
  { w: "เนซึโกะ", en: "Nezuko", cat: "anime", lv: 2 },
  { w: "เอเรน", en: "Eren Yeager", cat: "anime", lv: 2 },
  { w: "ไททัน", en: "Titan", cat: "anime", lv: 2 },
  { w: "โกโจ ซาโตรุ", en: "Gojo Satoru", cat: "anime", lv: 2 },
  { w: "ไซตามะ", en: "Saitama", cat: "anime", lv: 2 },
  { w: "เดกุ", en: "Deku", cat: "anime", lv: 2 },
  { w: "เอ็ดเวิร์ด เอลริค", en: "Edward Elric", cat: "anime", lv: 3 },
  { w: "อิคคิวซัง", en: "Ikkyu-san", cat: "anime", lv: 3 },
  { w: "เจ้าหนูอะตอม", en: "Astro Boy", cat: "anime", lv: 2 },
  { w: "ลูฟี่หมวกฟาง", en: "Straw Hat", cat: "anime", lv: 1 },

  /* ---------- ภาพยนตร์ / ซีรีส์ ---------- */
  { w: "ซูเปอร์แมน", en: "Superman", cat: "movie", lv: 1 },
  { w: "แบทแมน", en: "Batman", cat: "movie", lv: 1 },
  { w: "สไปเดอร์แมน", en: "Spider-Man", cat: "movie", lv: 1 },
  { w: "ไอรอนแมน", en: "Iron Man", cat: "movie", lv: 1 },
  { w: "ธอร์", en: "Thor", cat: "movie", lv: 1 },
  { w: "ฮัลค์", en: "Hulk", cat: "movie", lv: 1 },
  { w: "กัปตันอเมริกา", en: "Captain America", cat: "movie", lv: 1 },
  { w: "กรูท", en: "Groot", cat: "movie", lv: 2 },
  { w: "โจ๊กเกอร์", en: "Joker", cat: "movie", lv: 1 },
  { w: "ฮาร์ลีย์ ควินน์", en: "Harley Quinn", cat: "movie", lv: 2 },
  { w: "วันเดอร์วูแมน", en: "Wonder Woman", cat: "movie", lv: 2 },
  { w: "แฟลช", en: "The Flash", cat: "movie", lv: 2 },
  { w: "อควาแมน", en: "Aquaman", cat: "movie", lv: 2 },
  { w: "ดาร์ธ เวเดอร์", en: "Darth Vader", cat: "movie", lv: 1 },
  { w: "โยดา", en: "Yoda", cat: "movie", lv: 1 },
  { w: "อาร์ทู-ดีทู", en: "R2-D2", cat: "movie", lv: 1 },
  { w: "ชิวแบคก้า", en: "Chewbacca", cat: "movie", lv: 2 },
  { w: "สตอร์มทรูปเปอร์", en: "Stormtrooper", cat: "movie", lv: 1 },
  { w: "แฮร์รี่ พอตเตอร์", en: "Harry Potter", cat: "movie", lv: 1 },
  { w: "เฮอร์ไมโอนี่", en: "Hermione", cat: "movie", lv: 2 },
  { w: "โวลเดอมอร์", en: "Voldemort", cat: "movie", lv: 2 },
  { w: "ด็อบบี้", en: "Dobby", cat: "movie", lv: 2 },
  { w: "กอลลั่ม", en: "Gollum", cat: "movie", lv: 2 },
  { w: "แจ็ค สแปร์โรว์", en: "Jack Sparrow", cat: "movie", lv: 1 },
  { w: "อี.ที.", en: "E.T.", cat: "movie", lv: 2 },
  { w: "คิงคอง", en: "King Kong", cat: "movie", lv: 1 },
  { w: "ก็อดซิลล่า", en: "Godzilla", cat: "movie", lv: 1 },
  { w: "เทอร์มิเนเตอร์", en: "Terminator", cat: "movie", lv: 2 },
  { w: "ออพติมัส ไพรม์", en: "Optimus Prime", cat: "movie", lv: 2 },
  { w: "แฟรงเกนสไตน์", en: "Frankenstein", cat: "movie", lv: 1 },
  { w: "แดร็กคูล่า", en: "Dracula", cat: "movie", lv: 1 },
  { w: "มัมมี่", en: "Mummy", cat: "movie", lv: 1 },
  { w: "มนุษย์หมาป่า", en: "Werewolf", cat: "movie", lv: 2 },
  { w: "ชาร์ลี แชปลิน", en: "Charlie Chaplin", cat: "movie", lv: 2 },
  { w: "อินเดียน่า โจนส์", en: "Indiana Jones", cat: "movie", lv: 2 },
  { w: "เจมส์ บอนด์", en: "James Bond", cat: "movie", lv: 2 },
  { w: "ฟอร์เรสต์ กัมป์", en: "Forrest Gump", cat: "movie", lv: 3 },
  { w: "เอเลี่ยน", en: "Alien", cat: "movie", lv: 2 },
  { w: "พรีเดเตอร์", en: "Predator", cat: "movie", lv: 3 },
  { w: "รถไทม์แมชชีน", en: "DeLorean", cat: "movie", lv: 3 },

  /* ---------- เกม ---------- */
  { w: "มาริโอ", en: "Mario", cat: "game", lv: 1 },
  { w: "ลุยจิ", en: "Luigi", cat: "game", lv: 1 },
  { w: "โยชิ", en: "Yoshi", cat: "game", lv: 1 },
  { w: "บาวเซอร์", en: "Bowser", cat: "game", lv: 2 },
  { w: "เจ้าหญิงพีช", en: "Princess Peach", cat: "game", lv: 2 },
  { w: "เห็ดมาริโอ", en: "Super Mushroom", cat: "game", lv: 1 },
  { w: "โซนิค", en: "Sonic", cat: "game", lv: 1 },
  { w: "ลิงก์", en: "Link", cat: "game", lv: 2 },
  { w: "เคอร์บี้", en: "Kirby", cat: "game", lv: 1 },
  { w: "แพคแมน", en: "Pac-Man", cat: "game", lv: 1 },
  { w: "เตตริส", en: "Tetris", cat: "game", lv: 1 },
  { w: "ครีปเปอร์", en: "Creeper", cat: "game", lv: 1 },
  { w: "สตีฟ", en: "Steve (Minecraft)", cat: "game", lv: 2 },
  { w: "ดาบเพชร", en: "Diamond Sword", cat: "game", lv: 2 },
  { w: "มาสเตอร์ ชีฟ", en: "Master Chief", cat: "game", lv: 3 },
  { w: "คราโตส", en: "Kratos", cat: "game", lv: 3 },
  { w: "ลาร่า ครอฟท์", en: "Lara Croft", cat: "game", lv: 3 },
  { w: "เมก้าแมน", en: "Mega Man", cat: "game", lv: 2 },
  { w: "ดองกี้คอง", en: "Donkey Kong", cat: "game", lv: 2 },
  { w: "ริว", en: "Ryu", cat: "game", lv: 3 },
  { w: "อะมองอัส", en: "Among Us crewmate", cat: "game", lv: 1 },
  { w: "แองกรี้เบิร์ดสีแดง", en: "Red bird", cat: "game", lv: 2 }

];
