/* คลังคำชุดที่ 2 — ตัวละครดัง
   ต่อท้าย characters.js ต้องโหลดหลัง characters.js เสมอ
   เก็บเป็นชื่อข้อความเท่านั้น ไม่มีรูปตัวละครใน repo นี้ */

window.WORDS_CHARACTERS = (window.WORDS_CHARACTERS || []).concat([

  /* ---------- การ์ตูน ---------- */
  { w: "พลูโต", en: "Pluto", cat: "cartoon", lv: 2 },
  { w: "ชิพกับเดล", en: "Chip 'n Dale", cat: "cartoon", lv: 2 },
  { w: "ดัมโบ้", en: "Dumbo", cat: "cartoon", lv: 1 },
  { w: "แบมบี้", en: "Bambi", cat: "cartoon", lv: 2 },
  { w: "ทิมอนกับพุมบ้า", en: "Timon and Pumbaa", cat: "cartoon", lv: 2 },
  { w: "มูฟาซา", en: "Mufasa", cat: "cartoon", lv: 3 },
  { w: "เจ้าหญิงจัสมิน", en: "Jasmine", cat: "cartoon", lv: 3 },
  { w: "จินนี่", en: "Genie", cat: "cartoon", lv: 1 },
  { w: "เจ้าชายกบ", en: "Frog Prince", cat: "cartoon", lv: 2 },
  { w: "ราพันเซล", en: "Rapunzel", cat: "cartoon", lv: 1 },
  { w: "โมอาน่า", en: "Moana", cat: "cartoon", lv: 2 },
  { w: "เมาอี", en: "Maui", cat: "cartoon", lv: 3 },
  { w: "เบย์แมกซ์", en: "Baymax", cat: "cartoon", lv: 1 },
  { w: "แจ็ค สเกลลิงตัน", en: "Jack Skellington", cat: "cartoon", lv: 2 },
  { w: "วอลล์-อี", en: "WALL-E", cat: "cartoon", lv: 1 },
  { w: "เรมี่หนูยอดเชฟ", en: "Remy", cat: "cartoon", lv: 2 },
  { w: "ซัลลี่", en: "Sulley", cat: "cartoon", lv: 2 },
  { w: "ไมค์ วาซาวสกี้", en: "Mike Wazowski", cat: "cartoon", lv: 1 },
  { w: "ไลท์นิ่ง แมคควีน", en: "Lightning McQueen", cat: "cartoon", lv: 1 },
  { w: "มิสเตอร์อินเครดิเบิล", en: "Mr. Incredible", cat: "cartoon", lv: 2 },
  { w: "แอสเทอริกซ์", en: "Asterix", cat: "cartoon", lv: 2 },
  { w: "โอเบลิกซ์", en: "Obelix", cat: "cartoon", lv: 2 },
  { w: "ตินติน", en: "Tintin", cat: "cartoon", lv: 2 },
  { w: "สเมิร์ฟ", en: "Smurf", cat: "cartoon", lv: 1 },
  { w: "ป๊อปอาย", en: "Popeye", cat: "cartoon", lv: 1 },
  { w: "เดอะฟลินท์สโตนส์", en: "The Flintstones", cat: "cartoon", lv: 3 },
  { w: "โรดรันเนอร์", en: "Road Runner", cat: "cartoon", lv: 2 },
  { w: "ทวีตี้", en: "Tweety", cat: "cartoon", lv: 2 },
  { w: "ดัฟฟี่ ดั๊ก", en: "Daffy Duck", cat: "cartoon", lv: 2 },
  { w: "เดอะมาสก์", en: "The Mask", cat: "cartoon", lv: 2 },
  { w: "แกรี่หอยทาก", en: "Gary the Snail", cat: "cartoon", lv: 2 },
  { w: "สควิดเวิร์ด", en: "Squidward", cat: "cartoon", lv: 2 },
  { w: "มิสเตอร์แครบ", en: "Mr. Krabs", cat: "cartoon", lv: 2 },
  { w: "ลิซ่า ซิมป์สัน", en: "Lisa Simpson", cat: "cartoon", lv: 2 },
  { w: "เดอะกริ๊นช์", en: "The Grinch", cat: "cartoon", lv: 2 },
  { w: "ป๊อปปาย ซานตาคลอส", en: "Santa Claus", cat: "cartoon", lv: 1 },

  /* ---------- อนิเมะ ---------- */
  { w: "ชิซูกะ", en: "Shizuka", cat: "anime", lv: 2 },
  { w: "ไจแอนท์", en: "Gian", cat: "anime", lv: 2 },
  { w: "ซูเนโอะ", en: "Suneo", cat: "anime", lv: 3 },
  { w: "ไทม์แมชชีนลิ้นชัก", en: "Time Machine drawer", cat: "anime", lv: 3 },
  { w: "คอปเตอร์ไม้ไผ่", en: "Take-copter", cat: "anime", lv: 2 },
  { w: "ประตูไปที่ไหนก็ได้", en: "Anywhere Door", cat: "anime", lv: 2 },
  { w: "อิทาจิ", en: "Itachi", cat: "anime", lv: 3 },
  { w: "ฮินาตะ", en: "Hinata", cat: "anime", lv: 3 },
  { w: "คูราม่า", en: "Kurama", cat: "anime", lv: 3 },
  { w: "แนมิ", en: "Nami", cat: "anime", lv: 2 },
  { w: "ซันจิ", en: "Sanji", cat: "anime", lv: 3 },
  { w: "อุซป", en: "Usopp", cat: "anime", lv: 3 },
  { w: "เรือโกอิ้งเมอร์รี่", en: "Going Merry", cat: "anime", lv: 3 },
  { w: "ธงโจรสลัดหมวกฟาง", en: "Straw Hat Jolly Roger", cat: "anime", lv: 2 },
  { w: "โกฮัง", en: "Gohan", cat: "anime", lv: 3 },
  { w: "พิคโกโร่", en: "Piccolo", cat: "anime", lv: 2 },
  { w: "ฟรีเซอร์", en: "Frieza", cat: "anime", lv: 3 },
  { w: "ชินราน", en: "Ran Mouri", cat: "anime", lv: 3 },
  { w: "คิด เดอะแฟนธ่อม", en: "Kaito Kid", cat: "anime", lv: 3 },
  { w: "ฮิมาวาริ", en: "Himawari", cat: "anime", lv: 3 },
  { w: "ชิโร่", en: "Shiro (Shin-chan's dog)", cat: "anime", lv: 3 },
  { w: "ลูน่า แมวเซเลอร์มูน", en: "Luna", cat: "anime", lv: 3 },
  { w: "โพนโย", en: "Ponyo", cat: "anime", lv: 2 },
  { w: "คิคิแม่มดน้อย", en: "Kiki", cat: "anime", lv: 2 },
  { w: "โนแฟซ", en: "No-Face", cat: "anime", lv: 2 },
  { w: "ปราสาทเวทมนตร์ของฮาวล์", en: "Howl's Moving Castle", cat: "anime", lv: 3 },
  { w: "คาลซิเฟอร์", en: "Calcifer", cat: "anime", lv: 3 },
  { w: "โพเกมอนอีวุย", en: "Eevee", cat: "anime", lv: 2 },
  { w: "ชาร์มานเดอร์", en: "Charmander", cat: "anime", lv: 1 },
  { w: "บัลบาซอร์", en: "Bulbasaur", cat: "anime", lv: 2 },
  { w: "สควิร์เทิล", en: "Squirtle", cat: "anime", lv: 2 },
  { w: "สนอร์แลกซ์", en: "Snorlax", cat: "anime", lv: 2 },
  { w: "มิวทู", en: "Mewtwo", cat: "anime", lv: 3 },
  { w: "เซนิตสึ", en: "Zenitsu", cat: "anime", lv: 3 },
  { w: "อิโนสึเกะ", en: "Inosuke", cat: "anime", lv: 3 },
  { w: "มิคาสะ", en: "Mikasa", cat: "anime", lv: 3 },
  { w: "เลวี", en: "Levi", cat: "anime", lv: 3 },
  { w: "เจนอส", en: "Genos", cat: "anime", lv: 3 },
  { w: "อิตาดาริ ยูจิ", en: "Yuji Itadori", cat: "anime", lv: 3 },
  { w: "อัลฟองส์ เอลริค", en: "Alphonse Elric", cat: "anime", lv: 3 },
  { w: "เคโรโระ", en: "Keroro", cat: "anime", lv: 3 },
  { w: "โคนัน เดอะบอย", en: "Conan the Boy", cat: "anime", lv: 3 },
  { w: "แมวจรจัดจิจิ", en: "Jiji", cat: "anime", lv: 3 },
  { w: "โปเกมอนไดโกลส", en: "Diglett", cat: "anime", lv: 3 },
  { w: "โมโมทาโร่", en: "Momotaro", cat: "anime", lv: 3 },

  /* ---------- ภาพยนตร์ ---------- */
  { w: "ลูก สกายวอล์คเกอร์", en: "Luke Skywalker", cat: "movie", lv: 2 },
  { w: "เจ้าหญิงเลอา", en: "Princess Leia", cat: "movie", lv: 2 },
  { w: "ฮาน โซโล", en: "Han Solo", cat: "movie", lv: 3 },
  { w: "บีบี-เอต", en: "BB-8", cat: "movie", lv: 2 },
  { w: "ซีทรีพีโอ", en: "C-3PO", cat: "movie", lv: 2 },
  { w: "ดาวมรณะ", en: "Death Star", cat: "movie", lv: 2 },
  { w: "กระบี่แสง", en: "lightsaber", cat: "movie", lv: 1 },
  { w: "แฮกริด", en: "Hagrid", cat: "movie", lv: 3 },
  { w: "ดัมเบิลดอร์", en: "Dumbledore", cat: "movie", lv: 2 },
  { w: "รอน วีสลีย์", en: "Ron Weasley", cat: "movie", lv: 3 },
  { w: "สเนป", en: "Snape", cat: "movie", lv: 3 },
  { w: "หมวกคัดสรร", en: "Sorting Hat", cat: "movie", lv: 2 },
  { w: "ไม้กวาดนิมบัส", en: "Nimbus broom", cat: "movie", lv: 3 },
  { w: "แกนดัล์ฟ", en: "Gandalf", cat: "movie", lv: 2 },
  { w: "โฟรโด", en: "Frodo", cat: "movie", lv: 3 },
  { w: "แหวนเอก", en: "the One Ring", cat: "movie", lv: 2 },
  { w: "แบล็คแพนเธอร์", en: "Black Panther", cat: "movie", lv: 2 },
  { w: "ด็อกเตอร์ สเตรนจ์", en: "Doctor Strange", cat: "movie", lv: 2 },
  { w: "แอนท์แมน", en: "Ant-Man", cat: "movie", lv: 2 },
  { w: "แบล็ควิโดว์", en: "Black Widow", cat: "movie", lv: 3 },
  { w: "ธานอส", en: "Thanos", cat: "movie", lv: 2 },
  { w: "โลกิ", en: "Loki", cat: "movie", lv: 2 },
  { w: "ค้อนของธอร์", en: "Mjolnir", cat: "movie", lv: 2 },
  { w: "โล่กัปตันอเมริกา", en: "Cap's shield", cat: "movie", lv: 1 },
  { w: "โรบิน", en: "Robin", cat: "movie", lv: 3 },
  { w: "แบทม็อบิล", en: "Batmobile", cat: "movie", lv: 2 },
  { w: "เวน้อม", en: "Venom", cat: "movie", lv: 2 },
  { w: "เดดพูล", en: "Deadpool", cat: "movie", lv: 2 },
  { w: "วูล์ฟเวอรีน", en: "Wolverine", cat: "movie", lv: 2 },
  { w: "โยดาน้อย", en: "Grogu", cat: "movie", lv: 2 },
  { w: "แมนดาลอเรียน", en: "The Mandalorian", cat: "movie", lv: 3 },
  { w: "ที-เร็กซ์จูราสสิค", en: "Jurassic T-Rex", cat: "movie", lv: 1 },
  { w: "เวโลซิแรปเตอร์", en: "Velociraptor", cat: "movie", lv: 2 },
  { w: "รถ DeLorean", en: "DeLorean", cat: "movie", lv: 3 },
  { w: "บักส์ ไลฟ์", en: "A Bug's Life", cat: "movie", lv: 3 },
  { w: "โรงงานช็อกโกแลต", en: "Chocolate Factory", cat: "movie", lv: 2 },
  { w: "วิลลี่ วองก้า", en: "Willy Wonka", cat: "movie", lv: 3 },
  { w: "ผีชูชก", en: "Beetlejuice", cat: "movie", lv: 3 },
  { w: "โกสต์บัสเตอร์", en: "Ghostbusters", cat: "movie", lv: 2 },
  { w: "อโลฮาสติทช์", en: "Lilo and Stitch", cat: "movie", lv: 3 },

  /* ---------- เกม ---------- */
  { w: "เห็ดพิษมาริโอ", en: "Poison Mushroom", cat: "game", lv: 3 },
  { w: "ท่อเขียวมาริโอ", en: "Warp Pipe", cat: "game", lv: 1 },
  { w: "กูมบ้า", en: "Goomba", cat: "game", lv: 2 },
  { w: "คูปา", en: "Koopa Troopa", cat: "game", lv: 2 },
  { w: "เทลส์", en: "Tails", cat: "game", lv: 3 },
  { w: "ด็อกเตอร์เอ็กแมน", en: "Dr. Eggman", cat: "game", lv: 3 },
  { w: "แหวนทองโซนิค", en: "Sonic ring", cat: "game", lv: 2 },
  { w: "มาสเตอร์ซอร์ด", en: "Master Sword", cat: "game", lv: 2 },
  { w: "เจ้าหญิงเซลด้า", en: "Princess Zelda", cat: "game", lv: 3 },
  { w: "ผี Pac-Man", en: "Pac-Man ghost", cat: "game", lv: 1 },
  { w: "เอนเดอร์แมน", en: "Enderman", cat: "game", lv: 2 },
  { w: "หมูมายคราฟต์", en: "Minecraft pig", cat: "game", lv: 1 },
  { w: "จอบเพชร", en: "Diamond Pickaxe", cat: "game", lv: 2 },
  { w: "หีบสมบัติ", en: "treasure chest", cat: "game", lv: 1 },
  { w: "อิมโพสเตอร์", en: "Impostor", cat: "game", lv: 2 },
  { w: "หมูแองกรี้เบิร์ด", en: "green pig", cat: "game", lv: 2 },
  { w: "ชูริเคน", en: "shuriken", cat: "game", lv: 1 },
  { w: "โปเกเดกซ์", en: "Pokedex", cat: "game", lv: 3 },
  { w: "จอยสติ๊กเกมอาร์เคด", en: "arcade joystick", cat: "game", lv: 2 },
  { w: "เกมบอย", en: "Game Boy", cat: "game", lv: 2 },
  { w: "ตัวหมากเกมเศรษฐี", en: "Monopoly token", cat: "game", lv: 3 },
  { w: "งูกับบันได", en: "Snakes and Ladders", cat: "game", lv: 2 }

]);
