/* คลังคำ: หมวดทั่วไป
   รูปแบบ: { w: คำไทย, en: อังกฤษ, cat: หมวด, lv: 1 ง่าย / 2 กลาง / 3 ยาก }
   เพิ่มคำได้เลย ต่อท้ายในหมวดที่ตรงที่สุด แล้วส่ง Pull Request */

window.WORDS_GENERAL = [

  /* ---------- สัตว์ ---------- */
  { w: "ช้าง", en: "elephant", cat: "animal", lv: 1 },
  { w: "หมา", en: "dog", cat: "animal", lv: 1 },
  { w: "แมว", en: "cat", cat: "animal", lv: 1 },
  { w: "ปลา", en: "fish", cat: "animal", lv: 1 },
  { w: "นก", en: "bird", cat: "animal", lv: 1 },
  { w: "งู", en: "snake", cat: "animal", lv: 1 },
  { w: "กบ", en: "frog", cat: "animal", lv: 1 },
  { w: "ผีเสื้อ", en: "butterfly", cat: "animal", lv: 1 },
  { w: "ยีราฟ", en: "giraffe", cat: "animal", lv: 1 },
  { w: "ม้าลาย", en: "zebra", cat: "animal", lv: 1 },
  { w: "สิงโต", en: "lion", cat: "animal", lv: 1 },
  { w: "เสือ", en: "tiger", cat: "animal", lv: 1 },
  { w: "หมี", en: "bear", cat: "animal", lv: 1 },
  { w: "กระต่าย", en: "rabbit", cat: "animal", lv: 1 },
  { w: "เต่า", en: "turtle", cat: "animal", lv: 1 },
  { w: "ปู", en: "crab", cat: "animal", lv: 1 },
  { w: "กุ้ง", en: "shrimp", cat: "animal", lv: 1 },
  { w: "ปลาหมึก", en: "squid", cat: "animal", lv: 2 },
  { w: "ฉลาม", en: "shark", cat: "animal", lv: 1 },
  { w: "ปลาวาฬ", en: "whale", cat: "animal", lv: 1 },
  { w: "โลมา", en: "dolphin", cat: "animal", lv: 1 },
  { w: "เพนกวิน", en: "penguin", cat: "animal", lv: 1 },
  { w: "นกฮูก", en: "owl", cat: "animal", lv: 1 },
  { w: "ค้างคาว", en: "bat", cat: "animal", lv: 1 },
  { w: "แมงมุม", en: "spider", cat: "animal", lv: 1 },
  { w: "ผึ้ง", en: "bee", cat: "animal", lv: 1 },
  { w: "มด", en: "ant", cat: "animal", lv: 1 },
  { w: "หอยทาก", en: "snail", cat: "animal", lv: 1 },
  { w: "ไก่", en: "chicken", cat: "animal", lv: 1 },
  { w: "เป็ด", en: "duck", cat: "animal", lv: 1 },
  { w: "หมู", en: "pig", cat: "animal", lv: 1 },
  { w: "วัว", en: "cow", cat: "animal", lv: 1 },
  { w: "ควาย", en: "buffalo", cat: "animal", lv: 2 },
  { w: "แพะ", en: "goat", cat: "animal", lv: 2 },
  { w: "แกะ", en: "sheep", cat: "animal", lv: 1 },
  { w: "ม้า", en: "horse", cat: "animal", lv: 1 },
  { w: "ลิง", en: "monkey", cat: "animal", lv: 1 },
  { w: "จิงโจ้", en: "kangaroo", cat: "animal", lv: 1 },
  { w: "แพนด้า", en: "panda", cat: "animal", lv: 1 },
  { w: "โคอาลา", en: "koala", cat: "animal", lv: 2 },
  { w: "กอริลลา", en: "gorilla", cat: "animal", lv: 2 },
  { w: "แรด", en: "rhino", cat: "animal", lv: 2 },
  { w: "ฮิปโป", en: "hippo", cat: "animal", lv: 2 },
  { w: "จระเข้", en: "crocodile", cat: "animal", lv: 1 },
  { w: "กิ้งก่า", en: "lizard", cat: "animal", lv: 2 },
  { w: "ไดโนเสาร์", en: "dinosaur", cat: "animal", lv: 1 },
  { w: "ยูนิคอร์น", en: "unicorn", cat: "animal", lv: 1 },
  { w: "มังกร", en: "dragon", cat: "animal", lv: 1 },
  { w: "นกยูง", en: "peacock", cat: "animal", lv: 2 },
  { w: "หงส์", en: "swan", cat: "animal", lv: 2 },
  { w: "แมงกะพรุน", en: "jellyfish", cat: "animal", lv: 2 },
  { w: "ดาวทะเล", en: "starfish", cat: "animal", lv: 1 },
  { w: "อูฐ", en: "camel", cat: "animal", lv: 2 },
  { w: "หมาป่า", en: "wolf", cat: "animal", lv: 2 },
  { w: "สุนัขจิ้งจอก", en: "fox", cat: "animal", lv: 2 },
  { w: "กระรอก", en: "squirrel", cat: "animal", lv: 2 },
  { w: "เม่น", en: "hedgehog", cat: "animal", lv: 2 },
  { w: "ตุ่น", en: "mole", cat: "animal", lv: 3 },
  { w: "นกกระจอกเทศ", en: "ostrich", cat: "animal", lv: 2 },
  { w: "นกเพนกวินจักรพรรดิ", en: "emperor penguin", cat: "animal", lv: 3 },
  { w: "ตั๊กแตน", en: "grasshopper", cat: "animal", lv: 2 },
  { w: "แมลงปอ", en: "dragonfly", cat: "animal", lv: 2 },
  { w: "ไส้เดือน", en: "earthworm", cat: "animal", lv: 2 },
  { w: "ค้างคาวแวมไพร์", en: "vampire bat", cat: "animal", lv: 3 },
  { w: "ปลาดาว", en: "sea star", cat: "animal", lv: 1 },
  { w: "หมึกยักษ์", en: "octopus", cat: "animal", lv: 2 },
  { w: "ตัวนิ่ม", en: "pangolin", cat: "animal", lv: 3 },
  { w: "ตัวกินมด", en: "anteater", cat: "animal", lv: 3 },
  { w: "สลอธ", en: "sloth", cat: "animal", lv: 2 },
  { w: "อัลปาก้า", en: "alpaca", cat: "animal", lv: 3 },

  /* ---------- อาหาร ---------- */
  { w: "ข้าว", en: "rice", cat: "food", lv: 1 },
  { w: "ก๋วยเตี๋ยว", en: "noodles", cat: "food", lv: 1 },
  { w: "พิซซ่า", en: "pizza", cat: "food", lv: 1 },
  { w: "แฮมเบอร์เกอร์", en: "burger", cat: "food", lv: 1 },
  { w: "ไอศกรีม", en: "ice cream", cat: "food", lv: 1 },
  { w: "เค้ก", en: "cake", cat: "food", lv: 1 },
  { w: "โดนัท", en: "donut", cat: "food", lv: 1 },
  { w: "กล้วย", en: "banana", cat: "food", lv: 1 },
  { w: "แอปเปิล", en: "apple", cat: "food", lv: 1 },
  { w: "ส้ม", en: "orange", cat: "food", lv: 1 },
  { w: "แตงโม", en: "watermelon", cat: "food", lv: 1 },
  { w: "สับปะรด", en: "pineapple", cat: "food", lv: 1 },
  { w: "องุ่น", en: "grapes", cat: "food", lv: 1 },
  { w: "สตรอว์เบอร์รี", en: "strawberry", cat: "food", lv: 1 },
  { w: "ทุเรียน", en: "durian", cat: "food", lv: 1 },
  { w: "มะม่วง", en: "mango", cat: "food", lv: 1 },
  { w: "มะพร้าว", en: "coconut", cat: "food", lv: 1 },
  { w: "ไข่ดาว", en: "fried egg", cat: "food", lv: 1 },
  { w: "ขนมปัง", en: "bread", cat: "food", lv: 1 },
  { w: "ชานมไข่มุก", en: "bubble tea", cat: "food", lv: 1 },
  { w: "กาแฟ", en: "coffee", cat: "food", lv: 1 },
  { w: "เฟรนช์ฟรายส์", en: "french fries", cat: "food", lv: 1 },
  { w: "ไก่ทอด", en: "fried chicken", cat: "food", lv: 1 },
  { w: "ซูชิ", en: "sushi", cat: "food", lv: 1 },
  { w: "ราเมง", en: "ramen", cat: "food", lv: 2 },
  { w: "ทาโก้", en: "taco", cat: "food", lv: 2 },
  { w: "สปาเกตตี", en: "spaghetti", cat: "food", lv: 2 },
  { w: "ป๊อปคอร์น", en: "popcorn", cat: "food", lv: 1 },
  { w: "ลูกอม", en: "candy", cat: "food", lv: 1 },
  { w: "ช็อกโกแลต", en: "chocolate", cat: "food", lv: 1 },
  { w: "แพนเค้ก", en: "pancake", cat: "food", lv: 2 },
  { w: "ชีส", en: "cheese", cat: "food", lv: 1 },
  { w: "แครอท", en: "carrot", cat: "food", lv: 1 },
  { w: "มะเขือเทศ", en: "tomato", cat: "food", lv: 1 },
  { w: "ข้าวโพด", en: "corn", cat: "food", lv: 1 },
  { w: "พริก", en: "chili", cat: "food", lv: 1 },
  { w: "หัวหอม", en: "onion", cat: "food", lv: 2 },
  { w: "เห็ด", en: "mushroom", cat: "food", lv: 1 },
  { w: "ไข่เจียว", en: "omelette", cat: "food", lv: 2 },
  { w: "น้ำอัดลม", en: "soda", cat: "food", lv: 2 },
  { w: "แซนด์วิช", en: "sandwich", cat: "food", lv: 1 },
  { w: "ฮอทดอก", en: "hot dog", cat: "food", lv: 1 },
  { w: "พาย", en: "pie", cat: "food", lv: 2 },
  { w: "บะหมี่กึ่งสำเร็จรูป", en: "instant noodles", cat: "food", lv: 2 },
  { w: "ลูกชิ้นปิ้ง", en: "grilled meatballs", cat: "food", lv: 2 },

  /* ---------- ของใช้ ---------- */
  { w: "ร่ม", en: "umbrella", cat: "object", lv: 1 },
  { w: "แว่นตา", en: "glasses", cat: "object", lv: 1 },
  { w: "นาฬิกา", en: "clock", cat: "object", lv: 1 },
  { w: "โทรศัพท์", en: "phone", cat: "object", lv: 1 },
  { w: "คอมพิวเตอร์", en: "computer", cat: "object", lv: 1 },
  { w: "หนังสือ", en: "book", cat: "object", lv: 1 },
  { w: "ดินสอ", en: "pencil", cat: "object", lv: 1 },
  { w: "กรรไกร", en: "scissors", cat: "object", lv: 1 },
  { w: "กุญแจ", en: "key", cat: "object", lv: 1 },
  { w: "ค้อน", en: "hammer", cat: "object", lv: 1 },
  { w: "บันได", en: "ladder", cat: "object", lv: 1 },
  { w: "เก้าอี้", en: "chair", cat: "object", lv: 1 },
  { w: "โต๊ะ", en: "table", cat: "object", lv: 1 },
  { w: "เตียง", en: "bed", cat: "object", lv: 1 },
  { w: "ตู้เย็น", en: "fridge", cat: "object", lv: 1 },
  { w: "โทรทัศน์", en: "television", cat: "object", lv: 1 },
  { w: "พัดลม", en: "fan", cat: "object", lv: 1 },
  { w: "ไฟฉาย", en: "flashlight", cat: "object", lv: 1 },
  { w: "เทียน", en: "candle", cat: "object", lv: 1 },
  { w: "กระเป๋า", en: "bag", cat: "object", lv: 1 },
  { w: "รองเท้า", en: "shoes", cat: "object", lv: 1 },
  { w: "หมวก", en: "hat", cat: "object", lv: 1 },
  { w: "ถุงเท้า", en: "socks", cat: "object", lv: 1 },
  { w: "กระจก", en: "mirror", cat: "object", lv: 1 },
  { w: "หวี", en: "comb", cat: "object", lv: 1 },
  { w: "แปรงสีฟัน", en: "toothbrush", cat: "object", lv: 1 },
  { w: "ช้อนส้อม", en: "cutlery", cat: "object", lv: 1 },
  { w: "จาน", en: "plate", cat: "object", lv: 1 },
  { w: "แก้วน้ำ", en: "glass", cat: "object", lv: 1 },
  { w: "หม้อ", en: "pot", cat: "object", lv: 1 },
  { w: "กล้องถ่ายรูป", en: "camera", cat: "object", lv: 1 },
  { w: "หูฟัง", en: "headphones", cat: "object", lv: 1 },
  { w: "ลูกโป่ง", en: "balloon", cat: "object", lv: 1 },
  { w: "ว่าว", en: "kite", cat: "object", lv: 1 },
  { w: "ตุ๊กตาหมี", en: "teddy bear", cat: "object", lv: 1 },
  { w: "ไม้กวาด", en: "broom", cat: "object", lv: 1 },
  { w: "ถังขยะ", en: "trash can", cat: "object", lv: 1 },
  { w: "โซฟา", en: "sofa", cat: "object", lv: 2 },
  { w: "เครื่องซักผ้า", en: "washing machine", cat: "object", lv: 2 },
  { w: "ไมโครโฟน", en: "microphone", cat: "object", lv: 1 },
  { w: "กีตาร์", en: "guitar", cat: "object", lv: 1 },
  { w: "เปียโน", en: "piano", cat: "object", lv: 1 },
  { w: "กลอง", en: "drum", cat: "object", lv: 1 },
  { w: "ไวโอลิน", en: "violin", cat: "object", lv: 2 },
  { w: "ธนู", en: "bow and arrow", cat: "object", lv: 1 },
  { w: "ดาบ", en: "sword", cat: "object", lv: 1 },
  { w: "โล่", en: "shield", cat: "object", lv: 1 },
  { w: "มงกุฎ", en: "crown", cat: "object", lv: 1 },
  { w: "แหวน", en: "ring", cat: "object", lv: 1 },
  { w: "สร้อยคอ", en: "necklace", cat: "object", lv: 2 },
  { w: "เข็มทิศ", en: "compass", cat: "object", lv: 2 },
  { w: "แผนที่", en: "map", cat: "object", lv: 2 },
  { w: "กล้องส่องทางไกล", en: "binoculars", cat: "object", lv: 2 },
  { w: "ตาชั่ง", en: "scale", cat: "object", lv: 2 },
  { w: "นาฬิกาทราย", en: "hourglass", cat: "object", lv: 2 },
  { w: "โทรศัพท์สาธารณะ", en: "payphone", cat: "object", lv: 3 },
  { w: "เครื่องพิมพ์ดีด", en: "typewriter", cat: "object", lv: 3 },
  { w: "กล่องดนตรี", en: "music box", cat: "object", lv: 3 },
  { w: "ลูกโลก", en: "globe", cat: "object", lv: 2 },
  { w: "กล้องจุลทรรศน์", en: "microscope", cat: "object", lv: 3 },
  { w: "กล้องโทรทรรศน์", en: "telescope", cat: "object", lv: 2 },

  /* ---------- อาชีพ ---------- */
  { w: "หมอ", en: "doctor", cat: "job", lv: 1 },
  { w: "พยาบาล", en: "nurse", cat: "job", lv: 1 },
  { w: "ตำรวจ", en: "police", cat: "job", lv: 1 },
  { w: "นักดับเพลิง", en: "firefighter", cat: "job", lv: 1 },
  { w: "ครู", en: "teacher", cat: "job", lv: 1 },
  { w: "พ่อครัว", en: "chef", cat: "job", lv: 1 },
  { w: "นักบิน", en: "pilot", cat: "job", lv: 1 },
  { w: "ชาวนา", en: "farmer", cat: "job", lv: 1 },
  { w: "ชาวประมง", en: "fisherman", cat: "job", lv: 2 },
  { w: "นักบินอวกาศ", en: "astronaut", cat: "job", lv: 1 },
  { w: "จิตรกร", en: "painter", cat: "job", lv: 2 },
  { w: "นักร้อง", en: "singer", cat: "job", lv: 1 },
  { w: "นักเต้น", en: "dancer", cat: "job", lv: 1 },
  { w: "นักมายากล", en: "magician", cat: "job", lv: 1 },
  { w: "ตัวตลก", en: "clown", cat: "job", lv: 1 },
  { w: "โจรสลัด", en: "pirate", cat: "job", lv: 1 },
  { w: "อัศวิน", en: "knight", cat: "job", lv: 1 },
  { w: "นินจา", en: "ninja", cat: "job", lv: 1 },
  { w: "ซามูไร", en: "samurai", cat: "job", lv: 2 },
  { w: "แม่มด", en: "witch", cat: "job", lv: 1 },
  { w: "นักสืบ", en: "detective", cat: "job", lv: 2 },
  { w: "ทหาร", en: "soldier", cat: "job", lv: 1 },
  { w: "บุรุษไปรษณีย์", en: "mailman", cat: "job", lv: 2 },
  { w: "ช่างตัดผม", en: "barber", cat: "job", lv: 2 },
  { w: "ช่างภาพ", en: "photographer", cat: "job", lv: 2 },
  { w: "นักวิทยาศาสตร์", en: "scientist", cat: "job", lv: 2 },
  { w: "ทันตแพทย์", en: "dentist", cat: "job", lv: 2 },
  { w: "สัตวแพทย์", en: "veterinarian", cat: "job", lv: 3 },
  { w: "ผู้พิพากษา", en: "judge", cat: "job", lv: 2 },
  { w: "วาทยกร", en: "conductor", cat: "job", lv: 3 },
  { w: "นักโบราณคดี", en: "archaeologist", cat: "job", lv: 3 },
  { w: "บาริสต้า", en: "barista", cat: "job", lv: 2 },

  /* ---------- กริยา / ท่าทาง ---------- */
  { w: "วิ่ง", en: "run", cat: "action", lv: 1 },
  { w: "กระโดด", en: "jump", cat: "action", lv: 1 },
  { w: "ว่ายน้ำ", en: "swim", cat: "action", lv: 1 },
  { w: "นอนหลับ", en: "sleep", cat: "action", lv: 1 },
  { w: "ร้องไห้", en: "cry", cat: "action", lv: 1 },
  { w: "หัวเราะ", en: "laugh", cat: "action", lv: 1 },
  { w: "จาม", en: "sneeze", cat: "action", lv: 2 },
  { w: "หาว", en: "yawn", cat: "action", lv: 2 },
  { w: "ปีนเขา", en: "climb", cat: "action", lv: 1 },
  { w: "ตกบันได", en: "fall down stairs", cat: "action", lv: 2 },
  { w: "แปรงฟัน", en: "brush teeth", cat: "action", lv: 1 },
  { w: "อาบน้ำ", en: "shower", cat: "action", lv: 1 },
  { w: "ทำอาหาร", en: "cook", cat: "action", lv: 1 },
  { w: "ตกปลา", en: "fishing", cat: "action", lv: 1 },
  { w: "ถ่ายรูป", en: "take a photo", cat: "action", lv: 1 },
  { w: "เล่นเกม", en: "play games", cat: "action", lv: 2 },
  { w: "ขับรถ", en: "drive", cat: "action", lv: 1 },
  { w: "ยกน้ำหนัก", en: "lift weights", cat: "action", lv: 1 },
  { w: "โบกมือ", en: "wave", cat: "action", lv: 2 },
  { w: "ชกมวย", en: "boxing", cat: "action", lv: 1 },
  { w: "เดินสายไฟ", en: "wiring", cat: "action", lv: 3 },
  { w: "รดน้ำต้นไม้", en: "water plants", cat: "action", lv: 1 },
  { w: "กวาดบ้าน", en: "sweep the floor", cat: "action", lv: 2 },
  { w: "ต่อคิว", en: "queue up", cat: "action", lv: 3 },
  { w: "รถติด", en: "traffic jam", cat: "action", lv: 2 },
  { w: "ตื่นสาย", en: "wake up late", cat: "action", lv: 3 },

  /* ---------- สถานที่ ---------- */
  { w: "โรงเรียน", en: "school", cat: "place", lv: 1 },
  { w: "โรงพยาบาล", en: "hospital", cat: "place", lv: 1 },
  { w: "ธนาคาร", en: "bank", cat: "place", lv: 2 },
  { w: "ห้องสมุด", en: "library", cat: "place", lv: 2 },
  { w: "สนามบิน", en: "airport", cat: "place", lv: 1 },
  { w: "สวนสัตว์", en: "zoo", cat: "place", lv: 1 },
  { w: "สวนสนุก", en: "amusement park", cat: "place", lv: 1 },
  { w: "ชายหาด", en: "beach", cat: "place", lv: 1 },
  { w: "ทะเลทราย", en: "desert", cat: "place", lv: 1 },
  { w: "ป่า", en: "forest", cat: "place", lv: 1 },
  { w: "ถ้ำ", en: "cave", cat: "place", lv: 1 },
  { w: "ปราสาท", en: "castle", cat: "place", lv: 1 },
  { w: "ประภาคาร", en: "lighthouse", cat: "place", lv: 1 },
  { w: "สะพาน", en: "bridge", cat: "place", lv: 1 },
  { w: "ตลาด", en: "market", cat: "place", lv: 2 },
  { w: "ร้านกาแฟ", en: "cafe", cat: "place", lv: 2 },
  { w: "โรงหนัง", en: "cinema", cat: "place", lv: 2 },
  { w: "สนามฟุตบอล", en: "football field", cat: "place", lv: 1 },
  { w: "สุสาน", en: "graveyard", cat: "place", lv: 2 },
  { w: "ภูเขาไฟ", en: "volcano", cat: "place", lv: 1 },
  { w: "น้ำตก", en: "waterfall", cat: "place", lv: 1 },
  { w: "เกาะร้าง", en: "desert island", cat: "place", lv: 2 },
  { w: "พีระมิด", en: "pyramid", cat: "place", lv: 1 },
  { w: "หอไอเฟล", en: "Eiffel Tower", cat: "place", lv: 1 },
  { w: "กำแพงเมืองจีน", en: "Great Wall", cat: "place", lv: 2 },
  { w: "หอเอนปิซา", en: "Leaning Tower of Pisa", cat: "place", lv: 2 },
  { w: "เทพีเสรีภาพ", en: "Statue of Liberty", cat: "place", lv: 2 },

  /* ---------- ธรรมชาติ ---------- */
  { w: "ดวงอาทิตย์", en: "sun", cat: "nature", lv: 1 },
  { w: "ดวงจันทร์", en: "moon", cat: "nature", lv: 1 },
  { w: "ดาว", en: "star", cat: "nature", lv: 1 },
  { w: "เมฆ", en: "cloud", cat: "nature", lv: 1 },
  { w: "ฝน", en: "rain", cat: "nature", lv: 1 },
  { w: "หิมะ", en: "snow", cat: "nature", lv: 1 },
  { w: "สายฟ้า", en: "lightning", cat: "nature", lv: 1 },
  { w: "รุ้งกินน้ำ", en: "rainbow", cat: "nature", lv: 1 },
  { w: "ต้นไม้", en: "tree", cat: "nature", lv: 1 },
  { w: "ดอกไม้", en: "flower", cat: "nature", lv: 1 },
  { w: "กระบองเพชร", en: "cactus", cat: "nature", lv: 1 },
  { w: "ใบไม้", en: "leaf", cat: "nature", lv: 1 },
  { w: "ภูเขา", en: "mountain", cat: "nature", lv: 1 },
  { w: "แม่น้ำ", en: "river", cat: "nature", lv: 1 },
  { w: "ทะเล", en: "sea", cat: "nature", lv: 1 },
  { w: "เกาะ", en: "island", cat: "nature", lv: 1 },
  { w: "ทอร์นาโด", en: "tornado", cat: "nature", lv: 2 },
  { w: "แผ่นดินไหว", en: "earthquake", cat: "nature", lv: 3 },
  { w: "สึนามิ", en: "tsunami", cat: "nature", lv: 2 },
  { w: "ภูเขาน้ำแข็ง", en: "iceberg", cat: "nature", lv: 2 },
  { w: "ทางช้างเผือก", en: "Milky Way", cat: "nature", lv: 3 },
  { w: "สุริยุปราคา", en: "solar eclipse", cat: "nature", lv: 3 },

  /* ---------- กีฬา ---------- */
  { w: "ฟุตบอล", en: "football", cat: "sport", lv: 1 },
  { w: "บาสเกตบอล", en: "basketball", cat: "sport", lv: 1 },
  { w: "เทนนิส", en: "tennis", cat: "sport", lv: 1 },
  { w: "แบดมินตัน", en: "badminton", cat: "sport", lv: 1 },
  { w: "กอล์ฟ", en: "golf", cat: "sport", lv: 1 },
  { w: "ปิงปอง", en: "table tennis", cat: "sport", lv: 1 },
  { w: "โบว์ลิ่ง", en: "bowling", cat: "sport", lv: 1 },
  { w: "สเก็ตบอร์ด", en: "skateboard", cat: "sport", lv: 1 },
  { w: "โต้คลื่น", en: "surfing", cat: "sport", lv: 2 },
  { w: "ปีนผา", en: "rock climbing", cat: "sport", lv: 2 },
  { w: "โยคะ", en: "yoga", cat: "sport", lv: 2 },
  { w: "ยิงธนู", en: "archery", cat: "sport", lv: 2 },
  { w: "สกี", en: "skiing", cat: "sport", lv: 2 },
  { w: "ดำน้ำ", en: "diving", cat: "sport", lv: 2 },
  { w: "กระโดดร่ม", en: "skydiving", cat: "sport", lv: 2 },
  { w: "ยิมนาสติก", en: "gymnastics", cat: "sport", lv: 3 },

  /* ---------- ยานพาหนะ ---------- */
  { w: "รถยนต์", en: "car", cat: "vehicle", lv: 1 },
  { w: "จักรยาน", en: "bicycle", cat: "vehicle", lv: 1 },
  { w: "มอเตอร์ไซค์", en: "motorcycle", cat: "vehicle", lv: 1 },
  { w: "รถบัส", en: "bus", cat: "vehicle", lv: 1 },
  { w: "รถไฟ", en: "train", cat: "vehicle", lv: 1 },
  { w: "เครื่องบิน", en: "airplane", cat: "vehicle", lv: 1 },
  { w: "เฮลิคอปเตอร์", en: "helicopter", cat: "vehicle", lv: 1 },
  { w: "เรือ", en: "boat", cat: "vehicle", lv: 1 },
  { w: "เรือดำน้ำ", en: "submarine", cat: "vehicle", lv: 1 },
  { w: "จรวด", en: "rocket", cat: "vehicle", lv: 1 },
  { w: "รถถัง", en: "tank", cat: "vehicle", lv: 1 },
  { w: "รถแทรกเตอร์", en: "tractor", cat: "vehicle", lv: 2 },
  { w: "รถพยาบาล", en: "ambulance", cat: "vehicle", lv: 1 },
  { w: "รถดับเพลิง", en: "fire truck", cat: "vehicle", lv: 1 },
  { w: "บอลลูน", en: "hot air balloon", cat: "vehicle", lv: 1 },
  { w: "จานบิน", en: "UFO", cat: "vehicle", lv: 1 },
  { w: "สกูตเตอร์", en: "scooter", cat: "vehicle", lv: 2 },
  { w: "รถเข็นช้อปปิ้ง", en: "shopping cart", cat: "vehicle", lv: 2 }

];
