/* คลังคำชุดที่ 2 — หมวดทั่วไป
   ไฟล์นี้ต่อท้าย general.js ไม่ทับของเดิม
   ต้องโหลดหลัง general.js เสมอ */

window.WORDS_GENERAL = (window.WORDS_GENERAL || []).concat([

  /* ---------- สัตว์ เพิ่มเติม ---------- */
  { w: "เสือดาว", en: "leopard", cat: "animal", lv: 2 },
  { w: "เสือชีตาห์", en: "cheetah", cat: "animal", lv: 2 },
  { w: "ลา", en: "donkey", cat: "animal", lv: 2 },
  { w: "ลามะ", en: "llama", cat: "animal", lv: 2 },
  { w: "ยุง", en: "mosquito", cat: "animal", lv: 1 },
  { w: "แมลงวัน", en: "fly", cat: "animal", lv: 1 },
  { w: "ด้วง", en: "beetle", cat: "animal", lv: 2 },
  { w: "จิ้งจก", en: "house lizard", cat: "animal", lv: 2 },
  { w: "ตุ๊กแก", en: "gecko", cat: "animal", lv: 2 },
  { w: "คางคก", en: "toad", cat: "animal", lv: 2 },
  { w: "ปลาไหล", en: "eel", cat: "animal", lv: 2 },
  { w: "ปลากระเบน", en: "stingray", cat: "animal", lv: 2 },
  { w: "ม้าน้ำ", en: "seahorse", cat: "animal", lv: 1 },
  { w: "หอยนางรม", en: "oyster", cat: "animal", lv: 2 },
  { w: "กั้ง", en: "mantis shrimp", cat: "animal", lv: 3 },
  { w: "แมงป่อง", en: "scorpion", cat: "animal", lv: 1 },
  { w: "ตะขาบ", en: "centipede", cat: "animal", lv: 2 },
  { w: "หนอน", en: "caterpillar", cat: "animal", lv: 1 },
  { w: "ดักแด้", en: "cocoon", cat: "animal", lv: 2 },
  { w: "ลูกอ๊อด", en: "tadpole", cat: "animal", lv: 2 },
  { w: "ลูกเจี๊ยบ", en: "chick", cat: "animal", lv: 1 },
  { w: "นกฟลามิงโก", en: "flamingo", cat: "animal", lv: 1 },
  { w: "นกทูแคน", en: "toucan", cat: "animal", lv: 2 },
  { w: "นกแก้ว", en: "parrot", cat: "animal", lv: 1 },
  { w: "นกกระเรียน", en: "crane", cat: "animal", lv: 2 },
  { w: "นกนางนวล", en: "seagull", cat: "animal", lv: 2 },
  { w: "นกอินทรี", en: "eagle", cat: "animal", lv: 1 },
  { w: "เหยี่ยว", en: "hawk", cat: "animal", lv: 2 },
  { w: "อีกา", en: "crow", cat: "animal", lv: 1 },
  { w: "นกพิราบ", en: "pigeon", cat: "animal", lv: 1 },
  { w: "นกกระจอก", en: "sparrow", cat: "animal", lv: 2 },
  { w: "หนู", en: "mouse", cat: "animal", lv: 1 },
  { w: "แฮมสเตอร์", en: "hamster", cat: "animal", lv: 1 },
  { w: "บีเวอร์", en: "beaver", cat: "animal", lv: 2 },
  { w: "นาก", en: "otter", cat: "animal", lv: 2 },
  { w: "แมวน้ำ", en: "seal", cat: "animal", lv: 1 },
  { w: "วอลรัส", en: "walrus", cat: "animal", lv: 2 },
  { w: "หมีขั้วโลก", en: "polar bear", cat: "animal", lv: 1 },
  { w: "ไฮยีน่า", en: "hyena", cat: "animal", lv: 3 },
  { w: "กวาง", en: "deer", cat: "animal", lv: 1 },
  { w: "กวางเรนเดียร์", en: "reindeer", cat: "animal", lv: 1 },
  { w: "หมูป่า", en: "wild boar", cat: "animal", lv: 2 },
  { w: "เมียร์แคท", en: "meerkat", cat: "animal", lv: 2 },
  { w: "ชิมแปนซี", en: "chimpanzee", cat: "animal", lv: 2 },
  { w: "อุรังอุตัง", en: "orangutan", cat: "animal", lv: 2 },
  { w: "งูเห่า", en: "cobra", cat: "animal", lv: 1 },
  { w: "งูเหลือม", en: "python", cat: "animal", lv: 2 },
  { w: "กิ้งก่าคาเมเลียน", en: "chameleon", cat: "animal", lv: 2 },
  { w: "อิกัวนา", en: "iguana", cat: "animal", lv: 3 },
  { w: "มังกรโคโมโด", en: "komodo dragon", cat: "animal", lv: 3 },
  { w: "เต่าทะเล", en: "sea turtle", cat: "animal", lv: 1 },
  { w: "ปลาปักเป้า", en: "pufferfish", cat: "animal", lv: 1 },
  { w: "ปลาการ์ตูน", en: "clownfish", cat: "animal", lv: 1 },
  { w: "ปลาทอง", en: "goldfish", cat: "animal", lv: 1 },
  { w: "วาฬเพชฌฆาต", en: "orca", cat: "animal", lv: 2 },
  { w: "ฟีนิกซ์", en: "phoenix", cat: "animal", lv: 2 },
  { w: "เงือก", en: "mermaid", cat: "animal", lv: 1 },
  { w: "เซนทอร์", en: "centaur", cat: "animal", lv: 3 },
  { w: "มินอทอร์", en: "minotaur", cat: "animal", lv: 3 },
  { w: "ก็อบลิน", en: "goblin", cat: "animal", lv: 3 },

  /* ---------- อาหาร เพิ่มเติม ---------- */
  { w: "วาฟเฟิล", en: "waffle", cat: "food", lv: 1 },
  { w: "ครัวซองต์", en: "croissant", cat: "food", lv: 1 },
  { w: "เพรตเซล", en: "pretzel", cat: "food", lv: 2 },
  { w: "มัฟฟิน", en: "muffin", cat: "food", lv: 2 },
  { w: "คุกกี้", en: "cookie", cat: "food", lv: 1 },
  { w: "มาร์ชเมลโลว์", en: "marshmallow", cat: "food", lv: 2 },
  { w: "ลูกกวาดอมยิ้ม", en: "lollipop", cat: "food", lv: 1 },
  { w: "หมากฝรั่ง", en: "chewing gum", cat: "food", lv: 2 },
  { w: "น้ำผึ้ง", en: "honey", cat: "food", lv: 2 },
  { w: "เนย", en: "butter", cat: "food", lv: 2 },
  { w: "นม", en: "milk", cat: "food", lv: 1 },
  { w: "โยเกิร์ต", en: "yogurt", cat: "food", lv: 2 },
  { w: "ชีสเค้ก", en: "cheesecake", cat: "food", lv: 2 },
  { w: "บราวนี่", en: "brownie", cat: "food", lv: 2 },
  { w: "ไอศกรีมโคน", en: "ice cream cone", cat: "food", lv: 1 },
  { w: "น้ำแข็งใส", en: "shaved ice", cat: "food", lv: 2 },
  { w: "เลม่อน", en: "lemon", cat: "food", lv: 1 },
  { w: "มะนาว", en: "lime", cat: "food", lv: 1 },
  { w: "เชอร์รี", en: "cherry", cat: "food", lv: 1 },
  { w: "พีช", en: "peach", cat: "food", lv: 1 },
  { w: "ลูกแพร์", en: "pear", cat: "food", lv: 1 },
  { w: "กีวี", en: "kiwi", cat: "food", lv: 1 },
  { w: "อะโวคาโด", en: "avocado", cat: "food", lv: 1 },
  { w: "บลูเบอร์รี", en: "blueberry", cat: "food", lv: 2 },
  { w: "ฟักทอง", en: "pumpkin", cat: "food", lv: 1 },
  { w: "แตงกวา", en: "cucumber", cat: "food", lv: 1 },
  { w: "มันฝรั่ง", en: "potato", cat: "food", lv: 1 },
  { w: "บรอกโคลี", en: "broccoli", cat: "food", lv: 1 },
  { w: "กะหล่ำปลี", en: "cabbage", cat: "food", lv: 2 },
  { w: "ผักกาดหอม", en: "lettuce", cat: "food", lv: 2 },
  { w: "ถั่วลิสง", en: "peanut", cat: "food", lv: 1 },
  { w: "ข้าวโพดคั่ว", en: "popped corn", cat: "food", lv: 2 },
  { w: "ไส้กรอก", en: "sausage", cat: "food", lv: 1 },
  { w: "เบคอน", en: "bacon", cat: "food", lv: 1 },
  { w: "สเต๊ก", en: "steak", cat: "food", lv: 1 },
  { w: "ปีกไก่", en: "chicken wing", cat: "food", lv: 1 },
  { w: "หอยทอด", en: "oyster omelette", cat: "food", lv: 3 },
  { w: "เกี๊ยว", en: "dumpling", cat: "food", lv: 2 },
  { w: "ซาลาเปา", en: "steamed bun", cat: "food", lv: 1 },
  { w: "ขนมจีบ", en: "shumai", cat: "food", lv: 2 },
  { w: "เบอร์ริโต", en: "burrito", cat: "food", lv: 2 },
  { w: "เคบับ", en: "kebab", cat: "food", lv: 2 },
  { w: "ลาซานญ่า", en: "lasagna", cat: "food", lv: 2 },
  { w: "ซุปมิโสะ", en: "miso soup", cat: "food", lv: 3 },
  { w: "กิมจิ", en: "kimchi", cat: "food", lv: 2 },
  { w: "ตะเกียบ", en: "chopsticks", cat: "food", lv: 1 },

  /* ---------- ของใช้ เพิ่มเติม ---------- */
  { w: "เข็มขัด", en: "belt", cat: "object", lv: 1 },
  { w: "เนกไท", en: "necktie", cat: "object", lv: 1 },
  { w: "ผ้าพันคอ", en: "scarf", cat: "object", lv: 2 },
  { w: "ถุงมือ", en: "gloves", cat: "object", lv: 1 },
  { w: "รองเท้าบูท", en: "boots", cat: "object", lv: 1 },
  { w: "รองเท้าแตะ", en: "flip-flops", cat: "object", lv: 1 },
  { w: "แว่นกันแดด", en: "sunglasses", cat: "object", lv: 1 },
  { w: "นาฬิกาข้อมือ", en: "wristwatch", cat: "object", lv: 1 },
  { w: "กระเป๋าเป้", en: "backpack", cat: "object", lv: 1 },
  { w: "กระเป๋าเดินทาง", en: "suitcase", cat: "object", lv: 1 },
  { w: "ร่มชายหาด", en: "beach umbrella", cat: "object", lv: 2 },
  { w: "เก้าอี้ชายหาด", en: "deck chair", cat: "object", lv: 2 },
  { w: "เต็นท์", en: "tent", cat: "object", lv: 1 },
  { w: "ถุงนอน", en: "sleeping bag", cat: "object", lv: 2 },
  { w: "เตาปิ้งย่าง", en: "grill", cat: "object", lv: 2 },
  { w: "กระทะ", en: "frying pan", cat: "object", lv: 1 },
  { w: "มีด", en: "knife", cat: "object", lv: 1 },
  { w: "เขียง", en: "cutting board", cat: "object", lv: 2 },
  { w: "ที่เปิดขวด", en: "bottle opener", cat: "object", lv: 2 },
  { w: "กาน้ำชา", en: "teapot", cat: "object", lv: 1 },
  { w: "ขวดนม", en: "baby bottle", cat: "object", lv: 2 },
  { w: "รถเข็นเด็ก", en: "stroller", cat: "object", lv: 2 },
  { w: "ผ้าอ้อม", en: "diaper", cat: "object", lv: 2 },
  { w: "ลูกบอล", en: "ball", cat: "object", lv: 1 },
  { w: "ตัวต่อเลโก้", en: "lego brick", cat: "object", lv: 1 },
  { w: "หุ่นยนต์", en: "robot", cat: "object", lv: 1 },
  { w: "ลูกข่าง", en: "spinning top", cat: "object", lv: 1 },
  { w: "โยโย่", en: "yo-yo", cat: "object", lv: 1 },
  { w: "ลูกเต๋า", en: "dice", cat: "object", lv: 1 },
  { w: "ไพ่", en: "playing cards", cat: "object", lv: 1 },
  { w: "หมากรุก", en: "chess", cat: "object", lv: 1 },
  { w: "จิ๊กซอว์", en: "jigsaw puzzle", cat: "object", lv: 1 },
  { w: "ลูกบาศก์รูบิค", en: "rubik's cube", cat: "object", lv: 1 },
  { w: "จอยเกม", en: "game controller", cat: "object", lv: 1 },
  { w: "เมาส์", en: "computer mouse", cat: "object", lv: 1 },
  { w: "คีย์บอร์ด", en: "keyboard", cat: "object", lv: 1 },
  { w: "ปลั๊กไฟ", en: "power plug", cat: "object", lv: 1 },
  { w: "หลอดไฟ", en: "light bulb", cat: "object", lv: 1 },
  { w: "แบตเตอรี่", en: "battery", cat: "object", lv: 1 },
  { w: "ไขควง", en: "screwdriver", cat: "object", lv: 1 },
  { w: "ประแจ", en: "wrench", cat: "object", lv: 1 },
  { w: "เลื่อย", en: "saw", cat: "object", lv: 1 },
  { w: "ตะปู", en: "nail", cat: "object", lv: 1 },
  { w: "เทปกาว", en: "tape", cat: "object", lv: 2 },
  { w: "แม่กุญแจ", en: "padlock", cat: "object", lv: 1 },
  { w: "โซ่", en: "chain", cat: "object", lv: 1 },
  { w: "เชือก", en: "rope", cat: "object", lv: 1 },
  { w: "ตะกร้า", en: "basket", cat: "object", lv: 1 },
  { w: "ถังน้ำ", en: "bucket", cat: "object", lv: 1 },
  { w: "บัวรดน้ำ", en: "watering can", cat: "object", lv: 1 },
  { w: "ร่มกันฝนพับ", en: "folding umbrella", cat: "object", lv: 3 },
  { w: "กระดานโต้คลื่น", en: "surfboard", cat: "object", lv: 1 },
  { w: "ห่วงยาง", en: "swim ring", cat: "object", lv: 1 },
  { w: "แว่นดำน้ำ", en: "goggles", cat: "object", lv: 2 },
  { w: "ถังออกซิเจน", en: "oxygen tank", cat: "object", lv: 2 },
  { w: "ร่มชูชีพ", en: "parachute", cat: "object", lv: 1 },
  { w: "เข็มฉีดยา", en: "syringe", cat: "object", lv: 1 },
  { w: "พลาสเตอร์ยา", en: "band-aid", cat: "object", lv: 2 },
  { w: "หูฟังหมอ", en: "stethoscope", cat: "object", lv: 1 },
  { w: "ไม้เท้า", en: "walking stick", cat: "object", lv: 2 },
  { w: "รถเข็นผู้ป่วย", en: "wheelchair", cat: "object", lv: 1 },
  { w: "เปลญวน", en: "hammock", cat: "object", lv: 1 },
  { w: "โคมไฟ", en: "lamp", cat: "object", lv: 1 },
  { w: "นาฬิกาปลุก", en: "alarm clock", cat: "object", lv: 1 },
  { w: "หมอน", en: "pillow", cat: "object", lv: 1 },
  { w: "ผ้าห่ม", en: "blanket", cat: "object", lv: 1 },
  { w: "ม่าน", en: "curtain", cat: "object", lv: 2 },
  { w: "พรม", en: "carpet", cat: "object", lv: 2 },
  { w: "ประตู", en: "door", cat: "object", lv: 1 },
  { w: "หน้าต่าง", en: "window", cat: "object", lv: 1 },
  { w: "บันไดเลื่อน", en: "escalator", cat: "object", lv: 2 },
  { w: "ลิฟต์", en: "elevator", cat: "object", lv: 2 },
  { w: "ตู้เอทีเอ็ม", en: "ATM", cat: "object", lv: 2 },
  { w: "ตู้กดน้ำ", en: "vending machine", cat: "object", lv: 2 },
  { w: "ป้ายจราจร", en: "road sign", cat: "object", lv: 2 },
  { w: "ไฟจราจร", en: "traffic light", cat: "object", lv: 1 },
  { w: "เสาไฟถนน", en: "street lamp", cat: "object", lv: 1 },
  { w: "ตู้ไปรษณีย์", en: "mailbox", cat: "object", lv: 1 },
  { w: "ธง", en: "flag", cat: "object", lv: 1 },
  { w: "ระฆัง", en: "bell", cat: "object", lv: 1 },
  { w: "แตร", en: "trumpet", cat: "object", lv: 1 },
  { w: "แซกโซโฟน", en: "saxophone", cat: "object", lv: 2 },
  { w: "ฟลุต", en: "flute", cat: "object", lv: 2 },
  { w: "ฮาร์โมนิกา", en: "harmonica", cat: "object", lv: 3 },
  { w: "แอคคอร์เดียน", en: "accordion", cat: "object", lv: 3 },
  { w: "แผ่นเสียง", en: "vinyl record", cat: "object", lv: 2 },
  { w: "เทปคาสเซ็ต", en: "cassette tape", cat: "object", lv: 2 },

  /* ---------- ร่างกาย ---------- */
  { w: "ตา", en: "eye", cat: "body", lv: 1 },
  { w: "หู", en: "ear", cat: "body", lv: 1 },
  { w: "จมูก", en: "nose", cat: "body", lv: 1 },
  { w: "ปาก", en: "mouth", cat: "body", lv: 1 },
  { w: "ฟัน", en: "tooth", cat: "body", lv: 1 },
  { w: "ลิ้น", en: "tongue", cat: "body", lv: 1 },
  { w: "มือ", en: "hand", cat: "body", lv: 1 },
  { w: "เท้า", en: "foot", cat: "body", lv: 1 },
  { w: "หัวใจ", en: "heart", cat: "body", lv: 1 },
  { w: "สมอง", en: "brain", cat: "body", lv: 1 },
  { w: "กระดูก", en: "bone", cat: "body", lv: 1 },
  { w: "โครงกระดูก", en: "skeleton", cat: "body", lv: 1 },
  { w: "หัวกะโหลก", en: "skull", cat: "body", lv: 1 },
  { w: "ปอด", en: "lungs", cat: "body", lv: 2 },
  { w: "เส้นผม", en: "hair", cat: "body", lv: 2 },
  { w: "หนวด", en: "moustache", cat: "body", lv: 1 },
  { w: "เครา", en: "beard", cat: "body", lv: 1 },
  { w: "คิ้ว", en: "eyebrow", cat: "body", lv: 2 },
  { w: "ลายนิ้วมือ", en: "fingerprint", cat: "body", lv: 2 },
  { w: "รอยสัก", en: "tattoo", cat: "body", lv: 2 },

  /* ---------- อาชีพ เพิ่มเติม ---------- */
  { w: "คนขับแท็กซี่", en: "taxi driver", cat: "job", lv: 2 },
  { w: "พนักงานเสิร์ฟ", en: "waiter", cat: "job", lv: 2 },
  { w: "ยาม", en: "security guard", cat: "job", lv: 2 },
  { w: "ภารโรง", en: "janitor", cat: "job", lv: 2 },
  { w: "ช่างไม้", en: "carpenter", cat: "job", lv: 2 },
  { w: "ช่างเชื่อม", en: "welder", cat: "job", lv: 2 },
  { w: "ช่างประปา", en: "plumber", cat: "job", lv: 2 },
  { w: "ช่างไฟฟ้า", en: "electrician", cat: "job", lv: 2 },
  { w: "สถาปนิก", en: "architect", cat: "job", lv: 3 },
  { w: "โปรแกรมเมอร์", en: "programmer", cat: "job", lv: 2 },
  { w: "ยูทูปเบอร์", en: "youtuber", cat: "job", lv: 2 },
  { w: "ดีเจ", en: "DJ", cat: "job", lv: 1 },
  { w: "นักข่าว", en: "reporter", cat: "job", lv: 2 },
  { w: "บรรณารักษ์", en: "librarian", cat: "job", lv: 3 },
  { w: "คนสวน", en: "gardener", cat: "job", lv: 2 },
  { w: "คนเลี้ยงแกะ", en: "shepherd", cat: "job", lv: 2 },
  { w: "คนขายไอศกรีม", en: "ice cream vendor", cat: "job", lv: 2 },
  { w: "นักผจญภัย", en: "adventurer", cat: "job", lv: 3 },
  { w: "นักสำรวจขั้วโลก", en: "polar explorer", cat: "job", lv: 3 },
  { w: "ผู้ตัดสิน", en: "referee", cat: "job", lv: 2 },
  { w: "คนแบกกล้อง", en: "cameraman", cat: "job", lv: 2 },
  { w: "นางฟ้า", en: "angel", cat: "job", lv: 1 },
  { w: "ปีศาจ", en: "devil", cat: "job", lv: 1 },
  { w: "ผี", en: "ghost", cat: "job", lv: 1 },
  { w: "ซอมบี้", en: "zombie", cat: "job", lv: 1 },
  { w: "พ่อมด", en: "wizard", cat: "job", lv: 1 },
  { w: "ราชา", en: "king", cat: "job", lv: 1 },
  { w: "ราชินี", en: "queen", cat: "job", lv: 1 },
  { w: "ยักษ์", en: "giant", cat: "job", lv: 1 },
  { w: "คนแคระ", en: "dwarf", cat: "job", lv: 2 },

  /* ---------- กริยา เพิ่มเติม ---------- */
  { w: "เต้นรำ", en: "dance", cat: "action", lv: 1 },
  { w: "ร้องเพลง", en: "sing", cat: "action", lv: 1 },
  { w: "อ่านหนังสือ", en: "read", cat: "action", lv: 1 },
  { w: "เขียนจดหมาย", en: "write a letter", cat: "action", lv: 2 },
  { w: "คุยโทรศัพท์", en: "make a call", cat: "action", lv: 2 },
  { w: "ซักผ้า", en: "do laundry", cat: "action", lv: 2 },
  { w: "รีดผ้า", en: "iron clothes", cat: "action", lv: 2 },
  { w: "ล้างจาน", en: "wash dishes", cat: "action", lv: 2 },
  { w: "ตัดผม", en: "cut hair", cat: "action", lv: 2 },
  { w: "โกนหนวด", en: "shave", cat: "action", lv: 2 },
  { w: "ผูกเชือกรองเท้า", en: "tie shoelaces", cat: "action", lv: 2 },
  { w: "เป่าเทียน", en: "blow out candles", cat: "action", lv: 1 },
  { w: "แกะของขวัญ", en: "unwrap a gift", cat: "action", lv: 2 },
  { w: "กอด", en: "hug", cat: "action", lv: 1 },
  { w: "จับมือ", en: "shake hands", cat: "action", lv: 2 },
  { w: "ตบมือ", en: "clap", cat: "action", lv: 2 },
  { w: "ชี้นิ้ว", en: "point", cat: "action", lv: 2 },
  { w: "ยักไหล่", en: "shrug", cat: "action", lv: 3 },
  { w: "กระซิบ", en: "whisper", cat: "action", lv: 3 },
  { w: "ตะโกน", en: "shout", cat: "action", lv: 2 },
  { w: "สะดุด", en: "trip over", cat: "action", lv: 2 },
  { w: "ลื่นล้ม", en: "slip", cat: "action", lv: 2 },
  { w: "ปีนต้นไม้", en: "climb a tree", cat: "action", lv: 1 },
  { w: "ขุดหลุม", en: "dig a hole", cat: "action", lv: 1 },
  { w: "ปลูกต้นไม้", en: "plant a tree", cat: "action", lv: 1 },
  { w: "เก็บผลไม้", en: "pick fruit", cat: "action", lv: 2 },
  { w: "จูงหมาเดินเล่น", en: "walk the dog", cat: "action", lv: 1 },
  { w: "ให้อาหารนก", en: "feed the birds", cat: "action", lv: 2 },
  { w: "ดูดาว", en: "stargaze", cat: "action", lv: 2 },
  { w: "นั่งสมาธิ", en: "meditate", cat: "action", lv: 2 },
  { w: "แอบดู", en: "peek", cat: "action", lv: 3 },
  { w: "หลงทาง", en: "get lost", cat: "action", lv: 3 },
  { w: "เข็นรถเสีย", en: "push a broken car", cat: "action", lv: 3 },

  /* ---------- สถานที่ เพิ่มเติม ---------- */
  { w: "พิพิธภัณฑ์", en: "museum", cat: "place", lv: 2 },
  { w: "สวนสาธารณะ", en: "park", cat: "place", lv: 1 },
  { w: "สนามเด็กเล่น", en: "playground", cat: "place", lv: 1 },
  { w: "สวนน้ำ", en: "water park", cat: "place", lv: 1 },
  { w: "โรงยิม", en: "gym", cat: "place", lv: 2 },
  { w: "ร้านตัดผม", en: "barber shop", cat: "place", lv: 2 },
  { w: "ร้านหนังสือ", en: "bookstore", cat: "place", lv: 2 },
  { w: "ร้านขายยา", en: "pharmacy", cat: "place", lv: 2 },
  { w: "สถานีตำรวจ", en: "police station", cat: "place", lv: 2 },
  { w: "สถานีดับเพลิง", en: "fire station", cat: "place", lv: 2 },
  { w: "ปั๊มน้ำมัน", en: "gas station", cat: "place", lv: 2 },
  { w: "ที่จอดรถ", en: "parking lot", cat: "place", lv: 2 },
  { w: "อุโมงค์", en: "tunnel", cat: "place", lv: 1 },
  { w: "เขาวงกต", en: "maze", cat: "place", lv: 1 },
  { w: "หอคอย", en: "tower", cat: "place", lv: 1 },
  { w: "กังหันลม", en: "windmill", cat: "place", lv: 1 },
  { w: "โรงนา", en: "barn", cat: "place", lv: 1 },
  { w: "บ้านต้นไม้", en: "treehouse", cat: "place", lv: 1 },
  { w: "อิกลู", en: "igloo", cat: "place", lv: 1 },
  { w: "กระโจมอินเดียนแดง", en: "teepee", cat: "place", lv: 2 },
  { w: "ปราสาททราย", en: "sandcastle", cat: "place", lv: 1 },
  { w: "ซากปรักหักพัง", en: "ruins", cat: "place", lv: 3 },
  { w: "สถานีอวกาศ", en: "space station", cat: "place", lv: 2 },
  { w: "บ้านผีสิง", en: "haunted house", cat: "place", lv: 1 },
  { w: "ท่าเรือ", en: "harbor", cat: "place", lv: 2 },
  { w: "โคลอสเซียม", en: "Colosseum", cat: "place", lv: 2 },
  { w: "ทัชมาฮาล", en: "Taj Mahal", cat: "place", lv: 2 },
  { w: "สโตนเฮนจ์", en: "Stonehenge", cat: "place", lv: 2 },
  { w: "ภูเขาไฟฟูจิ", en: "Mount Fuji", cat: "place", lv: 1 },
  { w: "สฟิงซ์", en: "Sphinx", cat: "place", lv: 2 },

  /* ---------- ธรรมชาติ เพิ่มเติม ---------- */
  { w: "หมอก", en: "fog", cat: "nature", lv: 2 },
  { w: "ลมพายุ", en: "storm", cat: "nature", lv: 2 },
  { w: "เกล็ดหิมะ", en: "snowflake", cat: "nature", lv: 1 },
  { w: "น้ำแข็งย้อย", en: "icicle", cat: "nature", lv: 2 },
  { w: "หยดน้ำ", en: "water drop", cat: "nature", lv: 1 },
  { w: "คลื่น", en: "wave", cat: "nature", lv: 1 },
  { w: "ฟองสบู่", en: "bubble", cat: "nature", lv: 1 },
  { w: "ไฟ", en: "fire", cat: "nature", lv: 1 },
  { w: "ควัน", en: "smoke", cat: "nature", lv: 2 },
  { w: "ดาวตก", en: "shooting star", cat: "nature", lv: 1 },
  { w: "ดาวเคราะห์", en: "planet", cat: "nature", lv: 1 },
  { w: "ดาวเสาร์", en: "Saturn", cat: "nature", lv: 1 },
  { w: "หลุมดำ", en: "black hole", cat: "nature", lv: 2 },
  { w: "แสงเหนือ", en: "aurora", cat: "nature", lv: 3 },
  { w: "ทานตะวัน", en: "sunflower", cat: "nature", lv: 1 },
  { w: "กุหลาบ", en: "rose", cat: "nature", lv: 1 },
  { w: "ทิวลิป", en: "tulip", cat: "nature", lv: 1 },
  { w: "บัว", en: "lotus", cat: "nature", lv: 1 },
  { w: "ซากุระ", en: "cherry blossom", cat: "nature", lv: 1 },
  { w: "ต้นสน", en: "pine tree", cat: "nature", lv: 1 },
  { w: "ต้นปาล์ม", en: "palm tree", cat: "nature", lv: 1 },
  { w: "ต้นไผ่", en: "bamboo", cat: "nature", lv: 1 },
  { w: "เห็ดในป่า", en: "wild mushroom", cat: "nature", lv: 2 },
  { w: "รากไม้", en: "roots", cat: "nature", lv: 2 },
  { w: "หิน", en: "rock", cat: "nature", lv: 1 },
  { w: "เพชร", en: "diamond", cat: "nature", lv: 1 },
  { w: "ทราย", en: "sand", cat: "nature", lv: 2 },
  { w: "โอเอซิส", en: "oasis", cat: "nature", lv: 2 },

  /* ---------- กีฬา เพิ่มเติม ---------- */
  { w: "วอลเลย์บอล", en: "volleyball", cat: "sport", lv: 1 },
  { w: "เบสบอล", en: "baseball", cat: "sport", lv: 1 },
  { w: "รักบี้", en: "rugby", cat: "sport", lv: 2 },
  { w: "ฮอกกี้", en: "hockey", cat: "sport", lv: 2 },
  { w: "สเก็ตน้ำแข็ง", en: "ice skating", cat: "sport", lv: 2 },
  { w: "ปั่นจักรยานเสือภูเขา", en: "mountain biking", cat: "sport", lv: 2 },
  { w: "วิ่งมาราธอน", en: "marathon", cat: "sport", lv: 2 },
  { w: "กระโดดเชือก", en: "jump rope", cat: "sport", lv: 1 },
  { w: "ฮูลาฮูป", en: "hula hoop", cat: "sport", lv: 1 },
  { w: "ชักเย่อ", en: "tug of war", cat: "sport", lv: 1 },
  { w: "มวยปล้ำ", en: "wrestling", cat: "sport", lv: 2 },
  { w: "ฟันดาบ", en: "fencing", cat: "sport", lv: 2 },
  { w: "ยูโด", en: "judo", cat: "sport", lv: 2 },
  { w: "เทควันโด", en: "taekwondo", cat: "sport", lv: 2 },
  { w: "พายเรือคายัค", en: "kayaking", cat: "sport", lv: 2 },
  { w: "เล่นเซิร์ฟสเก็ต", en: "surfskate", cat: "sport", lv: 3 },

  /* ---------- ยานพาหนะ เพิ่มเติม ---------- */
  { w: "รถบรรทุก", en: "truck", cat: "vehicle", lv: 1 },
  { w: "รถขยะ", en: "garbage truck", cat: "vehicle", lv: 2 },
  { w: "รถเครน", en: "crane truck", cat: "vehicle", lv: 2 },
  { w: "รถตัก", en: "excavator", cat: "vehicle", lv: 2 },
  { w: "รถผสมปูน", en: "cement mixer", cat: "vehicle", lv: 2 },
  { w: "รถไฟใต้ดิน", en: "subway", cat: "vehicle", lv: 2 },
  { w: "รถราง", en: "tram", cat: "vehicle", lv: 2 },
  { w: "เรือใบ", en: "sailboat", cat: "vehicle", lv: 1 },
  { w: "เรือแคนู", en: "canoe", cat: "vehicle", lv: 1 },
  { w: "เรือสำราญ", en: "cruise ship", cat: "vehicle", lv: 2 },
  { w: "แพ", en: "raft", cat: "vehicle", lv: 1 },
  { w: "เจ็ตสกี", en: "jet ski", cat: "vehicle", lv: 2 },
  { w: "สโนว์โมบิล", en: "snowmobile", cat: "vehicle", lv: 3 },
  { w: "เลื่อนซานตา", en: "sleigh", cat: "vehicle", lv: 1 },
  { w: "รถม้า", en: "horse carriage", cat: "vehicle", lv: 1 },
  { w: "ไม้กวาดแม่มด", en: "flying broom", cat: "vehicle", lv: 1 },
  { w: "พรมวิเศษ", en: "magic carpet", cat: "vehicle", lv: 1 },
  { w: "โดรน", en: "drone", cat: "vehicle", lv: 1 },
  { w: "รถโรงเรียน", en: "school bus", cat: "vehicle", lv: 1 },
  { w: "รถไอศกรีม", en: "ice cream truck", cat: "vehicle", lv: 2 }

]);
