/* คลังคำชุดที่ 2 — หมวดไทย
   ต่อท้าย thai.js ต้องโหลดหลัง thai.js เสมอ */

window.WORDS_THAI = (window.WORDS_THAI || []).concat([

  /* ---------- อาหารไทย ---------- */
  { w: "ข้าวซอย", en: "khao soi", cat: "thai-food", lv: 2 },
  { w: "ไส้อั่ว", en: "sai ua", cat: "thai-food", lv: 3 },
  { w: "น้ำพริกอ่อง", en: "nam prik ong", cat: "thai-food", lv: 3 },
  { w: "แกงส้ม", en: "sour curry", cat: "thai-food", lv: 3 },
  { w: "ปลาราด", en: "fried fish with sauce", cat: "thai-food", lv: 3 },
  { w: "ยำวุ้นเส้น", en: "glass noodle salad", cat: "thai-food", lv: 2 },
  { w: "ลาบ", en: "larb", cat: "thai-food", lv: 3 },
  { w: "เนื้อน้ำตก", en: "nam tok salad", cat: "thai-food", lv: 3 },
  { w: "คอหมูย่าง", en: "grilled pork neck", cat: "thai-food", lv: 2 },
  { w: "ไก่ทอดหาดใหญ่", en: "Hat Yai fried chicken", cat: "thai-food", lv: 2 },
  { w: "ข้าวยำ", en: "khao yam", cat: "thai-food", lv: 3 },
  { w: "โรตีชาชัก", en: "roti with pulled tea", cat: "thai-food", lv: 2 },
  { w: "ข้าวหมกไก่", en: "khao mok gai", cat: "thai-food", lv: 3 },
  { w: "เต้าฮวย", en: "tofu pudding", cat: "thai-food", lv: 2 },
  { w: "บัวลอย", en: "bua loy", cat: "thai-food", lv: 2 },
  { w: "ตะโก้", en: "takoh", cat: "thai-food", lv: 3 },
  { w: "ขนมชั้น", en: "layered dessert", cat: "thai-food", lv: 2 },
  { w: "ขนมถ้วย", en: "khanom tuay", cat: "thai-food", lv: 3 },
  { w: "ข้าวเกรียบ", en: "rice cracker", cat: "thai-food", lv: 2 },
  { w: "ทับทิมกรอบ", en: "tub tim krob", cat: "thai-food", lv: 3 },
  { w: "น้ำเก๊กฮวย", en: "chrysanthemum drink", cat: "thai-food", lv: 3 },
  { w: "น้ำมะพร้าว", en: "coconut water", cat: "thai-food", lv: 1 },
  { w: "โอเลี้ยง", en: "thai iced black coffee", cat: "thai-food", lv: 3 },
  { w: "มะม่วงน้ำปลาหวาน", en: "mango with sweet fish sauce", cat: "thai-food", lv: 3 },
  { w: "มังคุด", en: "mangosteen", cat: "thai-food", lv: 1 },
  { w: "เงาะ", en: "rambutan", cat: "thai-food", lv: 1 },
  { w: "ลำไย", en: "longan", cat: "thai-food", lv: 2 },
  { w: "ลิ้นจี่", en: "lychee", cat: "thai-food", lv: 2 },
  { w: "ชมพู่", en: "rose apple", cat: "thai-food", lv: 2 },
  { w: "ฝรั่ง", en: "guava", cat: "thai-food", lv: 1 },
  { w: "มะละกอ", en: "papaya", cat: "thai-food", lv: 1 },
  { w: "ขนุน", en: "jackfruit", cat: "thai-food", lv: 2 },
  { w: "กระท้อน", en: "santol", cat: "thai-food", lv: 3 },
  { w: "ตะไคร้", en: "lemongrass", cat: "thai-food", lv: 2 },
  { w: "ใบเตย", en: "pandan leaf", cat: "thai-food", lv: 3 },
  { w: "กระเทียมดอง", en: "pickled garlic", cat: "thai-food", lv: 3 },

  /* ---------- วัฒนธรรม ---------- */
  { w: "รดน้ำดำหัว", en: "songkran blessing", cat: "thai-culture", lv: 3 },
  { w: "แห่นาค", en: "ordination parade", cat: "thai-culture", lv: 3 },
  { w: "ตักบาตร", en: "alms giving", cat: "thai-culture", lv: 2 },
  { w: "จุดธูป", en: "light incense", cat: "thai-culture", lv: 2 },
  { w: "เจดีย์", en: "pagoda", cat: "thai-culture", lv: 1 },
  { w: "พระพุทธรูป", en: "buddha statue", cat: "thai-culture", lv: 1 },
  { w: "ระฆังวัด", en: "temple bell", cat: "thai-culture", lv: 2 },
  { w: "กลองยาว", en: "long drum", cat: "thai-culture", lv: 2 },
  { w: "ระนาด", en: "ranat", cat: "thai-culture", lv: 3 },
  { w: "ขลุ่ย", en: "thai flute", cat: "thai-culture", lv: 2 },
  { w: "หนังตะลุง", en: "shadow puppet", cat: "thai-culture", lv: 2 },
  { w: "ลิเก", en: "likay", cat: "thai-culture", lv: 3 },
  { w: "มโนราห์", en: "manora dance", cat: "thai-culture", lv: 3 },
  { w: "ผ้าไหมไทย", en: "thai silk", cat: "thai-culture", lv: 3 },
  { w: "ชฎา", en: "thai headdress", cat: "thai-culture", lv: 2 },
  { w: "เล็บมือนาง", en: "dance nails", cat: "thai-culture", lv: 3 },
  { w: "ทศกัณฐ์", en: "Thotsakan", cat: "thai-culture", lv: 3 },
  { w: "พระอินทร์", en: "Indra", cat: "thai-culture", lv: 3 },
  { w: "กุมารทอง", en: "kuman thong", cat: "thai-culture", lv: 2 },
  { w: "ผีปอบ", en: "phi pop", cat: "thai-culture", lv: 3 },
  { w: "นางตะเคียน", en: "tree spirit", cat: "thai-culture", lv: 3 },
  { w: "ตะกรุด", en: "amulet", cat: "thai-culture", lv: 3 },
  { w: "สายสิญจน์", en: "sacred thread", cat: "thai-culture", lv: 3 },
  { w: "บายศรี", en: "bai sri", cat: "thai-culture", lv: 3 },
  { w: "ขันน้ำ", en: "water bowl", cat: "thai-culture", lv: 2 },
  { w: "ปี่กลองมวยไทย", en: "muay thai music", cat: "thai-culture", lv: 3 },
  { w: "มงคลมวยไทย", en: "mongkhon headband", cat: "thai-culture", lv: 3 },

  /* ---------- สถานที่ ---------- */
  { w: "หาดใหญ่", en: "Hat Yai", cat: "thai-place", lv: 3 },
  { w: "สงขลา", en: "Songkhla", cat: "thai-place", lv: 3 },
  { w: "นางเงือกสมิหลา", en: "Samila Mermaid", cat: "thai-place", lv: 3 },
  { w: "เกาะสมุย", en: "Koh Samui", cat: "thai-place", lv: 2 },
  { w: "เกาะเต่า", en: "Koh Tao", cat: "thai-place", lv: 2 },
  { w: "อ่าวมาหยา", en: "Maya Bay", cat: "thai-place", lv: 3 },
  { w: "เขาหลัก", en: "Khao Lak", cat: "thai-place", lv: 3 },
  { w: "ปาย", en: "Pai", cat: "thai-place", lv: 3 },
  { w: "ดอยสุเทพ", en: "Doi Suthep", cat: "thai-place", lv: 2 },
  { w: "อยุธยา", en: "Ayutthaya", cat: "thai-place", lv: 2 },
  { w: "สุโขทัย", en: "Sukhothai", cat: "thai-place", lv: 2 },
  { w: "ปราสาทหินพิมาย", en: "Phimai", cat: "thai-place", lv: 3 },
  { w: "วัดร่องขุ่น", en: "White Temple", cat: "thai-place", lv: 2 },
  { w: "ถนนข้าวสาร", en: "Khao San Road", cat: "thai-place", lv: 2 },
  { w: "อนุสาวรีย์ชัยสมรภูมิ", en: "Victory Monument", cat: "thai-place", lv: 3 },
  { w: "สนามหลวง", en: "Sanam Luang", cat: "thai-place", lv: 3 },

  /* ---------- ชีวิตประจำวัน ---------- */
  { w: "รถกระบะ", en: "pickup truck", cat: "thai-life", lv: 1 },
  { w: "เรือด่วนเจ้าพระยา", en: "river express boat", cat: "thai-life", lv: 3 },
  { w: "รถไฟดีเซลราง", en: "local train", cat: "thai-life", lv: 3 },
  { w: "ร้านก๋วยเตี๋ยวข้างทาง", en: "roadside noodle shop", cat: "thai-life", lv: 2 },
  { w: "โต๊ะพับพลาสติก", en: "plastic folding table", cat: "thai-life", lv: 3 },
  { w: "เก้าอี้พลาสติกแดง", en: "red plastic stool", cat: "thai-life", lv: 2 },
  { w: "หม้อก๋วยเตี๋ยว", en: "noodle pot", cat: "thai-life", lv: 3 },
  { w: "เตาถ่าน", en: "charcoal stove", cat: "thai-life", lv: 2 },
  { w: "กระติกน้ำแข็ง", en: "ice cooler", cat: "thai-life", lv: 2 },
  { w: "ตุ่มน้ำ", en: "water jar", cat: "thai-life", lv: 2 },
  { w: "ขันอาบน้ำ", en: "bathing bowl", cat: "thai-life", lv: 2 },
  { w: "ไม้แขวนเสื้อ", en: "clothes hanger", cat: "thai-life", lv: 1 },
  { w: "มุ้ง", en: "mosquito net", cat: "thai-life", lv: 2 },
  { w: "ไม้ตียุง", en: "electric fly swatter", cat: "thai-life", lv: 2 },
  { w: "หมูกระทะเตากลม", en: "moo kratha stove", cat: "thai-life", lv: 3 },
  { w: "เสื่อ", en: "woven mat", cat: "thai-life", lv: 2 },
  { w: "หมอนขิด", en: "triangle pillow", cat: "thai-life", lv: 3 },
  { w: "เปลไกวเด็ก", en: "baby hammock", cat: "thai-life", lv: 3 },
  { w: "กระด้ง", en: "winnowing basket", cat: "thai-life", lv: 3 },
  { w: "งอบชาวนา", en: "farmer hat", cat: "thai-life", lv: 2 },
  { w: "เคียวเกี่ยวข้าว", en: "sickle", cat: "thai-life", lv: 2 },
  { w: "ควายลากเกวียน", en: "buffalo cart", cat: "thai-life", lv: 2 },
  { w: "สวนยางพารา", en: "rubber plantation", cat: "thai-life", lv: 3 },
  { w: "เรือประมง", en: "fishing boat", cat: "thai-life", lv: 1 },
  { w: "แหจับปลา", en: "fishing net", cat: "thai-life", lv: 1 },
  { w: "ปลาตากแห้ง", en: "dried fish", cat: "thai-life", lv: 2 },
  { w: "ลอตเตอรี่", en: "lottery ticket", cat: "thai-life", lv: 2 },
  { w: "พัดสาน", en: "woven fan", cat: "thai-life", lv: 2 }

]);
