/* คลังคำ: หมวดไทย — อาหาร วัฒนธรรม สถานที่ ของใช้
   หมวด: thai-food / thai-culture / thai-place / thai-life */

window.WORDS_THAI = [

  /* ---------- อาหารไทย ---------- */
  { w: "ต้มยำกุ้ง", en: "tom yum goong", cat: "thai-food", lv: 1 },
  { w: "ผัดไทย", en: "pad thai", cat: "thai-food", lv: 1 },
  { w: "ส้มตำ", en: "som tam", cat: "thai-food", lv: 1 },
  { w: "ข้าวเหนียวมะม่วง", en: "mango sticky rice", cat: "thai-food", lv: 1 },
  { w: "ไก่ย่าง", en: "grilled chicken", cat: "thai-food", lv: 1 },
  { w: "หมูปิ้ง", en: "grilled pork skewer", cat: "thai-food", lv: 1 },
  { w: "ข้าวมันไก่", en: "chicken rice", cat: "thai-food", lv: 2 },
  { w: "ข้าวผัด", en: "fried rice", cat: "thai-food", lv: 1 },
  { w: "กะเพราไข่ดาว", en: "pad kaprao", cat: "thai-food", lv: 2 },
  { w: "แกงเขียวหวาน", en: "green curry", cat: "thai-food", lv: 2 },
  { w: "มัสมั่น", en: "massaman curry", cat: "thai-food", lv: 3 },
  { w: "ต้มข่าไก่", en: "tom kha gai", cat: "thai-food", lv: 3 },
  { w: "ก๋วยเตี๋ยวเรือ", en: "boat noodles", cat: "thai-food", lv: 2 },
  { w: "หมูกระทะ", en: "moo kratha", cat: "thai-food", lv: 1 },
  { w: "โรตี", en: "roti", cat: "thai-food", lv: 1 },
  { w: "ขนมครก", en: "khanom krok", cat: "thai-food", lv: 2 },
  { w: "ลอดช่อง", en: "lod chong", cat: "thai-food", lv: 2 },
  { w: "ทองหยิบ", en: "thong yip", cat: "thai-food", lv: 3 },
  { w: "ฝอยทอง", en: "foi thong", cat: "thai-food", lv: 3 },
  { w: "ชาไทย", en: "thai tea", cat: "thai-food", lv: 1 },
  { w: "น้ำปลา", en: "fish sauce", cat: "thai-food", lv: 2 },
  { w: "ครกกับสาก", en: "mortar and pestle", cat: "thai-food", lv: 1 },
  { w: "ปลาทู", en: "mackerel", cat: "thai-food", lv: 1 },
  { w: "ไข่เค็ม", en: "salted egg", cat: "thai-food", lv: 2 },
  { w: "กล้วยทอด", en: "fried banana", cat: "thai-food", lv: 1 },
  { w: "ข้าวเหนียวหมูปิ้ง", en: "sticky rice with pork", cat: "thai-food", lv: 2 },

  /* ---------- วัฒนธรรม / ประเพณี ---------- */
  { w: "ไหว้", en: "wai", cat: "thai-culture", lv: 1 },
  { w: "สงกรานต์", en: "Songkran", cat: "thai-culture", lv: 1 },
  { w: "ลอยกระทง", en: "Loy Krathong", cat: "thai-culture", lv: 1 },
  { w: "กระทง", en: "krathong", cat: "thai-culture", lv: 1 },
  { w: "โคมลอย", en: "sky lantern", cat: "thai-culture", lv: 1 },
  { w: "ปืนฉีดน้ำ", en: "water gun", cat: "thai-culture", lv: 1 },
  { w: "พระ", en: "monk", cat: "thai-culture", lv: 1 },
  { w: "บาตรพระ", en: "alms bowl", cat: "thai-culture", lv: 2 },
  { w: "ยักษ์วัดแจ้ง", en: "temple giant", cat: "thai-culture", lv: 2 },
  { w: "โขน", en: "khon mask dance", cat: "thai-culture", lv: 3 },
  { w: "รำไทย", en: "thai dance", cat: "thai-culture", lv: 2 },
  { w: "มวยไทย", en: "muay thai", cat: "thai-culture", lv: 1 },
  { w: "ตะกร้อ", en: "sepak takraw", cat: "thai-culture", lv: 1 },
  { w: "ว่าวจุฬา", en: "chula kite", cat: "thai-culture", lv: 3 },
  { w: "ช้างไทย", en: "thai elephant", cat: "thai-culture", lv: 1 },
  { w: "พวงมาลัย", en: "flower garland", cat: "thai-culture", lv: 1 },
  { w: "ศาลพระภูมิ", en: "spirit house", cat: "thai-culture", lv: 2 },
  { w: "ผ้าขาวม้า", en: "pha khao ma", cat: "thai-culture", lv: 2 },
  { w: "งูจงอาง", en: "king cobra", cat: "thai-culture", lv: 2 },
  { w: "ผีกระสือ", en: "krasue", cat: "thai-culture", lv: 2 },
  { w: "แม่นาค", en: "Mae Nak", cat: "thai-culture", lv: 3 },
  { w: "หนุมาน", en: "Hanuman", cat: "thai-culture", lv: 2 },
  { w: "ครุฑ", en: "Garuda", cat: "thai-culture", lv: 2 },
  { w: "นาค", en: "naga", cat: "thai-culture", lv: 2 },

  /* ---------- สถานที่ในไทย ---------- */
  { w: "วัดพระแก้ว", en: "Wat Phra Kaew", cat: "thai-place", lv: 2 },
  { w: "วัดอรุณ", en: "Wat Arun", cat: "thai-place", lv: 1 },
  { w: "ภูเขาทอง", en: "Golden Mount", cat: "thai-place", lv: 2 },
  { w: "สะพานข้ามแม่น้ำแคว", en: "Bridge over the River Kwai", cat: "thai-place", lv: 3 },
  { w: "ตลาดน้ำ", en: "floating market", cat: "thai-place", lv: 1 },
  { w: "หาดป่าตอง", en: "Patong Beach", cat: "thai-place", lv: 3 },
  { w: "ดอยอินทนนท์", en: "Doi Inthanon", cat: "thai-place", lv: 3 },
  { w: "เกาะพีพี", en: "Phi Phi Islands", cat: "thai-place", lv: 2 },
  { w: "สยามพารากอน", en: "Siam Paragon", cat: "thai-place", lv: 3 },
  { w: "จตุจักร", en: "Chatuchak Market", cat: "thai-place", lv: 2 },
  { w: "เยาวราช", en: "Chinatown Bangkok", cat: "thai-place", lv: 2 },
  { w: "หัวลำโพง", en: "Hua Lamphong station", cat: "thai-place", lv: 3 },

  /* ---------- ชีวิตประจำวันแบบไทย ---------- */
  { w: "ตุ๊กตุ๊ก", en: "tuk-tuk", cat: "thai-life", lv: 1 },
  { w: "รถสองแถว", en: "songthaew", cat: "thai-life", lv: 2 },
  { w: "เรือหางยาว", en: "longtail boat", cat: "thai-life", lv: 2 },
  { w: "รถไฟฟ้า BTS", en: "BTS skytrain", cat: "thai-life", lv: 2 },
  { w: "วินมอเตอร์ไซค์", en: "motorcycle taxi", cat: "thai-life", lv: 2 },
  { w: "รถเข็นขายของ", en: "street food cart", cat: "thai-life", lv: 2 },
  { w: "ร้านสะดวกซื้อ", en: "convenience store", cat: "thai-life", lv: 2 },
  { w: "พัดลมตั้งพื้น", en: "stand fan", cat: "thai-life", lv: 2 },
  { w: "ยาดม", en: "inhaler stick", cat: "thai-life", lv: 2 },
  { w: "ยาหม่อง", en: "balm", cat: "thai-life", lv: 2 },
  { w: "ถุงน้ำแข็งใส่หลอด", en: "drink in a bag", cat: "thai-life", lv: 2 },
  { w: "ชุดนักเรียนไทย", en: "thai school uniform", cat: "thai-life", lv: 2 },
  { w: "เสาชิงช้า", en: "Giant Swing", cat: "thai-life", lv: 3 },
  { w: "หมาจรจัด", en: "street dog", cat: "thai-life", lv: 1 },
  { w: "ฝนตกแดดออก", en: "sun shower", cat: "thai-life", lv: 3 },
  { w: "น้ำท่วม", en: "flood", cat: "thai-life", lv: 2 },
  { w: "ควายลงปลัก", en: "buffalo in mud", cat: "thai-life", lv: 3 },
  { w: "นาข้าว", en: "rice field", cat: "thai-life", lv: 1 }

];
